"use strict";

const CURATED_ITEMS = [
  { answer: "Eiffel Tower", aliases: ["la tour eiffel", "tour eiffel", "iron lady"], category: "Landmark", tier: 1 },
  { answer: "Mona Lisa", aliases: ["la gioconda", "la joconde", "monalisa"], category: "Artwork", tier: 1 },
  { answer: "Pikachu", aliases: ["pikachu pokemon", "pika"], category: "Game Character", tier: 1 },
  { answer: "Mario", aliases: ["super mario", "mario bros", "super mario bros"], category: "Game Character", tier: 1 },
  { answer: "Coca-Cola", aliases: ["coke", "coca cola"], category: "Brand", tier: 1 },
  { answer: "Big Ben", aliases: ["elizabeth tower", "the elizabeth tower", "big ben tower"], category: "Landmark", tier: 1 },
  { answer: "Statue of Liberty", aliases: ["liberty statue", "lady liberty", "statue liberty new york"], category: "Landmark", tier: 1 },
  { answer: "Golden Retriever", aliases: ["golden retriever dog", "golden retrievers", "golden"], category: "Animal", tier: 1 },
  { answer: "Pizza", aliases: ["pizzas"], category: "Food", tier: 1 },
  { answer: "iPhone", aliases: ["apple iphone", "i phone"], category: "Object", tier: 1, wiki: "IPhone" },
  { answer: "The Beatles", aliases: ["beatles", "beatles band"], category: "Band", tier: 1 },
  { answer: "Albert Einstein", aliases: ["einstein"], category: "Scientist", tier: 1 },
  { answer: "Batman", aliases: ["the batman"], category: "Movie Character", tier: 1 },
  { answer: "Darth Vader", aliases: ["vader", "lord vader"], category: "Movie Character", tier: 1 },
  { answer: "Harry Potter", aliases: ["harry potter series"], category: "Movie", tier: 1 },
  { answer: "William Shakespeare", aliases: ["shakespeare", "the bard", "shakespeare william"], category: "Author", tier: 1 },
  { answer: "Lion", aliases: ["lions"], category: "Animal", tier: 1 },
  { answer: "Giraffe", aliases: ["giraffes"], category: "Animal", tier: 1 },
  { answer: "The Moon", aliases: ["moon", "luna", "luna moon"], category: "Space", tier: 1, wiki: "Moon" },
  { answer: "The Sun", aliases: ["sun", "sol"], category: "Space", tier: 1, wiki: "Sun" },
  { answer: "Mars", aliases: ["planet mars", "the red planet"], category: "Space", tier: 1 },
  { answer: "Tyrannosaurus rex", aliases: ["t rex", "trex", "tyrannosaurus", "t-rex"], category: "Dinosaur", tier: 1, wiki: "Tyrannosaurus" },
  { answer: "Ice cream", aliases: ["icecream"], category: "Food", tier: 1 },
  { answer: "Hamburger", aliases: ["burger", "burgers"], category: "Food", tier: 1 },
  { answer: "Hot dog", aliases: ["hotdog"], category: "Food", tier: 1 },
  { answer: "Guitar", aliases: ["acoustic guitar"], category: "Object", tier: 1 },
  { answer: "Piano", aliases: ["grand piano"], category: "Music", tier: 1 },
  { answer: "Michael Jackson", aliases: ["mj", "jacko"], category: "Person", tier: 1 },
  { answer: "Taj Mahal", aliases: ["the taj mahal", "taj", "tajmahal", "taj mahal india"], category: "Landmark", tier: 1 },
  { answer: "Mount Everest", aliases: ["everest", "sagarmatha", "chomolungma", "sagarmatha everest"], category: "Landmark", tier: 1 },
  { answer: "Great Wall of China", aliases: ["the great wall", "great wall", "great wall china"], category: "Landmark", tier: 1 },
  { answer: "Titanic", aliases: ["rms titanic", "titanic 1997"], category: "Movie", tier: 1, wiki: "Titanic (1997 film)" },

  { answer: "Christ the Redeemer", aliases: ["cristo redentor", "christ the redeemer statue"], category: "Landmark", tier: 2, wiki: "Christ the Redeemer (statue)" },
  { answer: "Leaning Tower of Pisa", aliases: ["tower of pisa", "pisa tower", "pisa tower leaning"], category: "Landmark", tier: 2 },
  { answer: "Colosseum", aliases: ["coliseum", "flavian amphitheatre", "colosseum rome"], category: "Landmark", tier: 2 },
  { answer: "Sydney Opera House", aliases: ["sydney opera", "opera house"], category: "Landmark", tier: 2 },
  { answer: "Sagrada Família", aliases: ["sagrada familia"], category: "Landmark", tier: 2 },
  { answer: "Mount Fuji", aliases: ["fuji", "fujisan", "fujiyama", "mt fuji", "mount fuji japan"], category: "Landmark", tier: 2 },
  { answer: "Niagara Falls", aliases: ["niagara"], category: "Landmark", tier: 2 },
  { answer: "Grand Canyon", aliases: ["the grand canyon"], category: "Landmark", tier: 2 },
  { answer: "Great Barrier Reef", aliases: ["great barrier", "great barrier reef australia"], category: "Nature", tier: 2 },
  { answer: "Amazon Rainforest", aliases: ["the amazon", "amazon jungle", "the amazon rainforest"], category: "Nature", tier: 2 },
  { answer: "Sahara", aliases: ["sahara desert", "the sahara", "sahara desert sahara"], category: "Nature", tier: 2 },
  { answer: "Uluru", aliases: ["ayers rock", "ayer's rock", "uluru rock", "uluru australia"], category: "Landmark", tier: 2 },
  { answer: "Victoria Falls", aliases: ["victoria fall", "moci-oa-tunya", "mosi-oa-tunya"], category: "Landmark", tier: 2 },
  { answer: "Moai", aliases: ["easter island head", "easter island statues", "moai statues"], category: "Landmark", tier: 2 },
  { answer: "Great Sphinx of Giza", aliases: ["sphinx", "the sphinx", "giza sphinx"], category: "Landmark", tier: 2 },
  { answer: "Terracotta Army", aliases: ["terracotta warriors", "terracotta soldiers"], category: "Landmark", tier: 2 },
  { answer: "Tutankhamun", aliases: ["king tut", "tut", "tutankhamen"], category: "History", tier: 2 },
  { answer: "Cleopatra", aliases: ["cleopatra vii"], category: "History", tier: 2 },
  { answer: "Julius Caesar", aliases: ["caesar"], category: "History", tier: 2 },
  { answer: "Napoleon", aliases: ["napoleon bonaparte"], category: "History", tier: 2 },
  { answer: "Leonardo da Vinci", aliases: ["da vinci", "leonardo", "leonardo davinci"], category: "Person", tier: 2 },
  { answer: "Mahatma Gandhi", aliases: ["gandhi", "gandhi mahatma"], category: "Person", tier: 2 },
  { answer: "Abraham Lincoln", aliases: ["lincoln"], category: "Person", tier: 2 },
  { answer: "Anne Frank", aliases: ["ann frank", "anne frank diary"], category: "Person", tier: 2 },
  { answer: "Nelson Mandela", aliases: ["mandela"], category: "Person", tier: 2 },
  { answer: "Martin Luther King Jr.", aliases: ["mlk", "martin luther king"], category: "Person", tier: 2 },
  { answer: "Elizabeth II", aliases: ["queen elizabeth", "queen elizabeth ii"], category: "Person", tier: 2 },
  { answer: "Gold", aliases: ["gold element", "au", "aurum"], category: "Chemistry", tier: 2 },
  { answer: "Mercury", aliases: ["mercury element", "quicksilver", "hg"], category: "Chemistry", tier: 2, wiki: "Mercury (element)" },
  { answer: "Helium", aliases: ["he"], category: "Chemistry", tier: 2 },
  { answer: "Sulfur", aliases: ["sulphur", "brimstone"], category: "Chemistry", tier: 2 },
  { answer: "Diamond", aliases: ["diamonds"], category: "Chemistry", tier: 2 },
  { answer: "Caffeine", aliases: ["caffeine molecule", "caffiene"], category: "Chemistry", tier: 2 },
  { answer: "DNA", aliases: ["deoxyribonucleic acid", "dna helix", "dna molecule"], category: "Biology", tier: 2 },
  { answer: "Human Brain", aliases: ["brain", "human brain organ"], category: "Biology", tier: 2, wiki: "Human brain" },
  { answer: "Human Skeleton", aliases: ["skeleton", "bones"], category: "Biology", tier: 2, wiki: "Human skeleton" },
  { answer: "Human Eye", aliases: ["eye"], category: "Biology", tier: 2, wiki: "Human eye" },
  { answer: "Fingerprint", aliases: ["fingerprints", "finger print"], category: "Biology", tier: 2 },
  { answer: "Stethoscope", aliases: ["stethoscopes"], category: "Medicine", tier: 2 },
  { answer: "Syringe", aliases: ["hypodermic syringe", "needle"], category: "Medicine", tier: 2 },
  { answer: "X-ray", aliases: ["xray", "x ray", "radiograph"], category: "Medicine", tier: 2 },
  { answer: "Microscope", aliases: ["microscopes", "light microscope"], category: "Object", tier: 2 },
  { answer: "Telescope", aliases: ["refracting telescope"], category: "Object", tier: 2 },
  { answer: "Saturn", aliases: ["planet saturn", "saturn planet", "the ringed planet"], category: "Space", tier: 2 },
  { answer: "Jupiter", aliases: ["planet jupiter", "jupiter planet", "the gas giant"], category: "Space", tier: 2 },
  { answer: "Venus", aliases: ["venus planet", "morning star"], category: "Space", tier: 2, wiki: "Venus" },
  { answer: "Andromeda Galaxy", aliases: ["andromeda"], category: "Space", tier: 2 },
  { answer: "Milky Way", aliases: ["the milky way"], category: "Space", tier: 2 },
  { answer: "International Space Station", aliases: ["iss"], category: "Space", tier: 2 },
  { answer: "Apollo 11", aliases: ["apollo eleven", "apollo 11 mission"], category: "Space", tier: 2 },
  { answer: "Saturn V", aliases: ["saturn 5", "saturn five rocket", "saturn v rocket"], category: "Space", tier: 2 },
  { answer: "Hubble Space Telescope", aliases: ["hubble", "hubble telescope"], category: "Space", tier: 2 },
  { answer: "Wright Flyer", aliases: ["the wright flyer", "wright brothers plane", "first airplane", "first plane"], category: "History", tier: 2 },
  { answer: "Printing Press", aliases: ["the printing press"], category: "History", tier: 2, wiki: "Printing press" },
  { answer: "Phonograph", aliases: ["gramophone", "record player"], category: "Object", tier: 2 },
  { answer: "Vinyl Record", aliases: ["vinyl", "lp", "record"], category: "Object", tier: 2, wiki: "Phonograph record" },
  { answer: "Floppy Disk", aliases: ["diskette", "floppy"], category: "Object", tier: 2 },
  { answer: "Cassette Tape", aliases: ["cassette", "audio cassette"], category: "Object", tier: 2, wiki: "Cassette tape" },
  { answer: "Typewriter", aliases: ["type writer", "typewriters"], category: "Object", tier: 2 },
  { answer: "Hourglass", aliases: ["sand timer", "sandglass", "sand clock"], category: "Object", tier: 2 },
  { answer: "Compass", aliases: ["magnetic compass"], category: "Object", tier: 2 },
  { answer: "Rubik's Cube", aliases: ["rubiks cube", "rubik cube", "magic cube"], category: "Object", tier: 2 },
  { answer: "Lego", aliases: ["legos", "lego bricks"], category: "Object", tier: 2 },
  { answer: "Giant Panda", aliases: ["panda", "pandas"], category: "Animal", tier: 2, wiki: "Giant panda" },
  { answer: "Polar Bear", aliases: ["polar bears", "white bear", "ursus maritimus"], category: "Animal", tier: 2 },
  { answer: "Koala", aliases: ["koala bear"], category: "Animal", tier: 2 },
  { answer: "Kangaroo", aliases: ["kangaroos", "roo", "kangaroo animal"], category: "Animal", tier: 2 },
  { answer: "Zebra", aliases: ["zebras"], category: "Animal", tier: 2 },
  { answer: "Emperor Penguin", aliases: ["penguin"], category: "Animal", tier: 2, wiki: "Emperor penguin" },
  { answer: "Flamingo", aliases: ["flamingos"], category: "Animal", tier: 2 },
  { answer: "Bald Eagle", aliases: ["eagle", "american eagle"], category: "Animal", tier: 2 },
  { answer: "Orca", aliases: ["killer whale", "orca whale"], category: "Animal", tier: 2, wiki: "Orca" },
  { answer: "Blue Whale", aliases: ["blue whales", "balaenoptera musculus"], category: "Animal", tier: 2 },
  { answer: "Dolphin", aliases: ["dolphins"], category: "Animal", tier: 2 },
  { answer: "Great White Shark", aliases: ["great white", "white shark"], category: "Animal", tier: 2 },
  { answer: "Octopus", aliases: ["octopi", "octopuses"], category: "Animal", tier: 2 },
  { answer: "Jellyfish", aliases: ["jelly fish"], category: "Animal", tier: 2 },
  { answer: "Butterfly", aliases: ["monarch butterfly", "butterflies"], category: "Animal", tier: 2, wiki: "Monarch butterfly" },
  { answer: "Bee", aliases: ["honey bee", "honeybee", "bumblebee"], category: "Animal", tier: 2, wiki: "Western honey bee" },
  { answer: "Sunflower", aliases: ["sunflowers"], category: "Plant", tier: 2, wiki: "Common sunflower" },
  { answer: "Cactus", aliases: ["cacti", "cactuses"], category: "Plant", tier: 2 },
  { answer: "Venus Flytrap", aliases: ["flytrap", "venus fly trap"], category: "Plant", tier: 2 },
  { answer: "Bonsai", aliases: ["bonsai tree"], category: "Plant", tier: 2 },
  { answer: "Bamboo", aliases: ["bamboo plant"], category: "Plant", tier: 2 },
  { answer: "Croissant", aliases: ["croissants"], category: "Food", tier: 2 },
  { answer: "Taco", aliases: ["tacos"], category: "Food", tier: 2 },
  { answer: "Ramen", aliases: ["ramen noodles"], category: "Food", tier: 2 },
  { answer: "Sushi", aliases: ["sushi roll", "sushis", "nigiri"], category: "Food", tier: 2 },
  { answer: "Chocolate", aliases: ["chocolates", "chocolate bar"], category: "Food", tier: 2 },
  { answer: "Banana", aliases: ["bananas"], category: "Food", tier: 2 },
  { answer: "Pineapple", aliases: ["pineapples"], category: "Food", tier: 2 },
  { answer: "Avocado", aliases: ["avocados"], category: "Food", tier: 2 },
  { answer: "Watermelon", aliases: ["watermelons"], category: "Food", tier: 2 },
  { answer: "Pretzel", aliases: ["pretzels"], category: "Food", tier: 2 },
  { answer: "Doughnut", aliases: ["donut", "donuts", "doughnuts"], category: "Food", tier: 2 },
  { answer: "French Fries", aliases: ["fries", "chips"], category: "Food", tier: 2 },
  { answer: "Violin", aliases: ["fiddle"], category: "Music", tier: 2 },
  { answer: "Saxophone", aliases: ["sax"], category: "Music", tier: 2 },
  { answer: "Trumpet", aliases: ["trumpets"], category: "Music", tier: 2 },
  { answer: "Drum Kit", aliases: ["drums", "drum set"], category: "Music", tier: 2, wiki: "Drum kit" },
  { answer: "Harp", aliases: ["harps"], category: "Music", tier: 2 },
  { answer: "Accordion", aliases: ["squeezebox"], category: "Music", tier: 2 },
  { answer: "Mozart", aliases: ["wolfgang amadeus mozart", "amadeus"], category: "Composer", tier: 2, wiki: "Wolfgang Amadeus Mozart" },
  { answer: "Beethoven", aliases: ["ludwig van beethoven"], category: "Composer", tier: 2, wiki: "Ludwig van Beethoven" },
  { answer: "Bach", aliases: ["johann sebastian bach", "j s bach"], category: "Composer", tier: 2, wiki: "Johann Sebastian Bach" },
  { answer: "Sumo", aliases: ["sumo wrestling"], category: "Sport", tier: 2 },
  { answer: "Archery", aliases: ["archer", "bow and arrow"], category: "Sport", tier: 2 },
  { answer: "Bowling", aliases: ["ten pin bowling"], category: "Sport", tier: 2 },
  { answer: "Table Tennis", aliases: ["ping pong"], category: "Sport", tier: 2 },
  { answer: "Skateboarding", aliases: ["skateboard"], category: "Sport", tier: 2 },
  { answer: "Surfing", aliases: ["surfboard", "surf"], category: "Sport", tier: 2 },
  { answer: "Chess", aliases: ["chess board", "chessboard"], category: "Game", tier: 2 },
  { answer: "Jenga", aliases: ["jenga game", "jenga tower"], category: "Game", tier: 2 },
  { answer: "Yo-yo", aliases: ["yoyo", "yo yo"], category: "Game", tier: 2 },
  { answer: "Light Bulb", aliases: ["lightbulb", "bulb", "the light bulb"], category: "Object", tier: 2, wiki: "Incandescent light bulb" },
  { answer: "Wind Turbine", aliases: ["wind turbines"], category: "Object", tier: 2 },
  { answer: "Ferris Wheel", aliases: ["ferriswheel"], category: "Object", tier: 2 },
  { answer: "Roller Coaster", aliases: ["rollercoaster"], category: "Object", tier: 2 },
  { answer: "Carousel", aliases: ["merry go round", "merry-go-round", "carrousel"], category: "Object", tier: 2 },
  { answer: "Pinball", aliases: ["pinball machine"], category: "Game", tier: 2 },
  { answer: "Magnet", aliases: ["magnets", "horseshoe magnet"], category: "Physics", tier: 2 },
  { answer: "Lightning", aliases: ["lightning bolt", "thunderbolt"], category: "Physics", tier: 2 },
  { answer: "Rainbow", aliases: ["rainbows"], category: "Physics", tier: 2 },
  { answer: "Newton's Cradle", aliases: ["newtons cradle", "newton cradle"], category: "Physics", tier: 2 },
  { answer: "Tesla Coil", aliases: ["tesla coils"], category: "Physics", tier: 2 },
  { answer: "Isaac Newton", aliases: ["newton", "sir isaac newton"], category: "Scientist", tier: 2 },
  { answer: "Marie Curie", aliases: ["curie", "madame curie"], category: "Scientist", tier: 2 },
  { answer: "Nikola Tesla", aliases: ["tesla"], category: "Scientist", tier: 2 },
  { answer: "Stephen Hawking", aliases: ["hawking"], category: "Scientist", tier: 2 },
  { answer: "Charles Darwin", aliases: ["darwin"], category: "Scientist", tier: 2 },
  { answer: "Galileo Galilei", aliases: ["galileo"], category: "Scientist", tier: 2 },
  { answer: "The Scream", aliases: ["scream", "the scream munch", "skrik"], category: "Artwork", tier: 2 },
  { answer: "The Starry Night", aliases: ["starry night", "starry night van gogh"], category: "Artwork", tier: 2 },
  { answer: "David", aliases: ["michelangelo david", "statue of david", "david statue"], category: "Artwork", tier: 2, wiki: "David (Michelangelo)" },
  { answer: "Venus de Milo", aliases: ["venus statue", "aphrodite of milos"], category: "Artwork", tier: 2 },
  { answer: "The Thinker", aliases: ["thinker", "rodin thinker", "le penseur"], category: "Artwork", tier: 2 },
  { answer: "Girl with a Pearl Earring", aliases: ["girl with pearl earring"], category: "Artwork", tier: 2 },
  { answer: "The Great Wave", aliases: ["great wave", "the great wave off kanagawa", "great wave off kanagawa"], category: "Artwork", tier: 2, wiki: "The Great Wave off Kanagawa" },
  { answer: "Parthenon", aliases: ["the parthenon"], category: "Landmark", tier: 2 },
  { answer: "Notre-Dame", aliases: ["notre dame", "notre dame cathedral", "notre dame de paris"], category: "Landmark", tier: 2, wiki: "Notre-Dame de Paris" },
  { answer: "Saint Basil's Cathedral", aliases: ["st basils cathedral", "st basil cathedral", "basils cathedral"], category: "Landmark", tier: 2 },
  { answer: "Hagia Sophia", aliases: ["ayasofya", "hagia sophia mosque", "sancta sophia"], category: "Landmark", tier: 2 },
  { answer: "Chichén Itzá", aliases: ["chichen itza", "el castillo"], category: "Landmark", tier: 2, wiki: "Chichen Itza" },
  { answer: "Petra", aliases: ["petra jordan"], category: "Landmark", tier: 2 },
  { answer: "Neuschwanstein Castle", aliases: ["neuschwanstein"], category: "Landmark", tier: 2 },
  { answer: "Elephant", aliases: ["african elephant", "african bush elephant"], category: "Animal", tier: 2, wiki: "African bush elephant" },
  { answer: "Hippopotamus", aliases: ["hippo", "hippos", "hippopotamus animal"], category: "Animal", tier: 2 },
  { answer: "Rhinoceros", aliases: ["rhino", "rhinos", "rhinoceros animal"], category: "Animal", tier: 2 },
  { answer: "Cheetah", aliases: ["cheetahs"], category: "Animal", tier: 2 },
  { answer: "Gorilla", aliases: ["gorillas"], category: "Animal", tier: 2 },
  { answer: "Camel", aliases: ["camels"], category: "Animal", tier: 2 },
  { answer: "Crocodile", aliases: ["crocs", "crocodiles"], category: "Animal", tier: 2 },
  { answer: "Tetris", aliases: ["tetris game", "tetris blocks"], category: "Game", tier: 2 },

  { answer: "Machu Picchu", aliases: ["machupicchu", "machu picchu ruins"], category: "Landmark", tier: 3 },
  { answer: "Stonehenge", aliases: ["stone henge"], category: "Landmark", tier: 3 },
  { answer: "Angkor Wat", aliases: ["ankor wat", "angkor wat temple"], category: "Landmark", tier: 3 },
  { answer: "Mont-Saint-Michel", aliases: ["mont saint michel", "mont st michel", "le mont saint michel"], category: "Landmark", tier: 3 },
  { answer: "Aqueduct of Segovia", aliases: ["segovia aqueduct", "the aqueduct of segovia"], category: "Landmark", tier: 3 },
  { answer: "Salar de Uyuni", aliases: ["uyuni", "salt flats", "uyuni salt flats"], category: "Nature", tier: 3 },
  { answer: "Great Blue Hole", aliases: ["the great blue hole", "blue hole belize"], category: "Nature", tier: 3 },
  { answer: "Galápagos Islands", aliases: ["galapagos", "the galapagos"], category: "Nature", tier: 3 },
  { answer: "Yellowstone National Park", aliases: ["yellowstone"], category: "Nature", tier: 3 },
  { answer: "Old Faithful", aliases: ["old faithful geyser"], category: "Nature", tier: 3 },
  { answer: "Aurora", aliases: ["northern lights", "aurora borealis", "southern lights", "aurora australis"], category: "Nature", tier: 3 },
  { answer: "Tornado", aliases: ["tornadoes", "twister"], category: "Nature", tier: 3 },
  { answer: "Waterspout", aliases: ["water spout"], category: "Nature", tier: 3 },
  { answer: "Iceberg", aliases: ["icebergs"], category: "Nature", tier: 3 },
  { answer: "Glacier", aliases: ["glaciers"], category: "Nature", tier: 3 },
  { answer: "Geyser", aliases: ["geysers"], category: "Nature", tier: 3 },
  { answer: "Meteor Crater", aliases: ["barringer crater"], category: "Nature", tier: 3 },
  { answer: "Ammonite", aliases: ["ammonites"], category: "Fossil", tier: 3, wiki: "Ammonoidea" },
  { answer: "Archaeopteryx", aliases: ["archaeopteryx lithographica", "urvogel"], category: "Fossil", tier: 3 },
  { answer: "Triceratops", aliases: ["triceratops dinosaur", "trike"], category: "Dinosaur", tier: 3 },
  { answer: "Velociraptor", aliases: ["velociraptor dinosaur", "raptor", "velociraptors"], category: "Dinosaur", tier: 3 },
  { answer: "Stegosaurus", aliases: ["stegosaurus dinosaur", "stegosaur"], category: "Dinosaur", tier: 3 },
  { answer: "Platypus", aliases: ["duck billed platypus"], category: "Animal", tier: 3 },
  { answer: "Axolotl", aliases: ["axolotls", "mexican salamander", "walking fish"], category: "Animal", tier: 3 },
  { answer: "Red Panda", aliases: ["firefox"], category: "Animal", tier: 3, wiki: "Red panda" },
  { answer: "Meerkat", aliases: ["meerkats"], category: "Animal", tier: 3 },
  { answer: "Capybara", aliases: ["capybaras"], category: "Animal", tier: 3 },
  { answer: "Sloth", aliases: ["sloths"], category: "Animal", tier: 3 },
  { answer: "Chameleon", aliases: ["chameleons"], category: "Animal", tier: 3 },
  { answer: "Komodo Dragon", aliases: ["komodo", "komodo dragons"], category: "Animal", tier: 3 },
  { answer: "Narwhal", aliases: ["narwhals", "narwhale", "sea unicorn"], category: "Animal", tier: 3 },
  { answer: "Pufferfish", aliases: ["blowfish", "puffer fish", "fugu"], category: "Animal", tier: 3, wiki: "Tetraodontidae" },
  { answer: "Anglerfish", aliases: ["angler fish"], category: "Animal", tier: 3 },
  { answer: "Mantis Shrimp", aliases: ["mantis shrimps"], category: "Animal", tier: 3 },
  { answer: "Clownfish", aliases: ["clown fish", "anemonefish", "nemo fish"], category: "Animal", tier: 3 },
  { answer: "Seahorse", aliases: ["sea horse", "seahorses"], category: "Animal", tier: 3 },
  { answer: "Poison Dart Frog", aliases: ["poison arrow frog", "dart frog", "poison dart frogs"], category: "Animal", tier: 3 },
  { answer: "Praying Mantis", aliases: ["mantis", "praying mantids"], category: "Animal", tier: 3, wiki: "Mantis" },
  { answer: "Ladybug", aliases: ["ladybird", "ladybugs", "ladybirds", "lady beetle"], category: "Animal", tier: 3, wiki: "Coccinellidae" },
  { answer: "Tardigrade", aliases: ["water bear", "waterbear"], category: "Biology", tier: 3 },
  { answer: "Neuron", aliases: ["nerve cell", "neurons", "neurone"], category: "Biology", tier: 3 },
  { answer: "Bacteria", aliases: ["bacterium"], category: "Biology", tier: 3 },
  { answer: "Petri Dish", aliases: ["petri dish"], category: "Medicine", tier: 3 },
  { answer: "Geiger Counter", aliases: ["geiger counter"], category: "Physics", tier: 3 },
  { answer: "Cloud Chamber", aliases: ["cloud chambers"], category: "Physics", tier: 3 },
  { answer: "Superconductor", aliases: ["superconductivity", "superconducting magnet"], category: "Physics", tier: 3, wiki: "Superconductivity" },
  { answer: "Large Hadron Collider", aliases: ["lhc", "hadron collider"], category: "Physics", tier: 3 },
  { answer: "Gyroscope", aliases: ["gyroscopes"], category: "Physics", tier: 3 },
  { answer: "Pendulum", aliases: ["pendulums"], category: "Physics", tier: 3 },
  { answer: "Foucault Pendulum", aliases: ["foucaults pendulum"], category: "Physics", tier: 3 },
  { answer: "Cathode Ray Tube", aliases: ["crt"], category: "Physics", tier: 3 },
  { answer: "Vacuum Tube", aliases: ["thermionic valve", "electron tube", "vacuum tubes"], category: "Physics", tier: 3 },
  { answer: "Transistor", aliases: ["transistors"], category: "Physics", tier: 3 },
  { answer: "Periodic Table", aliases: ["the periodic table", "periodic table of elements"], category: "Chemistry", tier: 3 },
  { answer: "Buckyball", aliases: ["buckminsterfullerene", "c60", "fullerene", "bucky ball"], category: "Chemistry", tier: 3, wiki: "Buckminsterfullerene" },
  { answer: "Benzene", aliases: ["benzene ring"], category: "Chemistry", tier: 3 },
  { answer: "Aspirin", aliases: ["acetylsalicylic acid"], category: "Chemistry", tier: 3 },
  { answer: "Erlenmeyer Flask", aliases: ["erlenmeyer", "conical flask"], category: "Chemistry", tier: 3 },
  { answer: "Bunsen Burner", aliases: ["bunsen"], category: "Chemistry", tier: 3 },
  { answer: "Test Tube", aliases: ["test tubes", "testtube"], category: "Chemistry", tier: 3 },
  { answer: "Graduated Cylinder", aliases: ["measuring cylinder", "graduated cylinders"], category: "Chemistry", tier: 3 },
  { answer: "Volumetric Flask", aliases: ["volumetric flasks"], category: "Chemistry", tier: 3 },
  { answer: "Dmitri Mendeleev", aliases: ["mendeleev"], category: "Scientist", tier: 3 },
  { answer: "Rosalind Franklin", aliases: ["franklin"], category: "Scientist", tier: 3 },
  { answer: "Max Planck", aliases: ["planck"], category: "Scientist", tier: 3 },
  { answer: "Niels Bohr", aliases: ["bohr"], category: "Scientist", tier: 3 },
  { answer: "Erwin Schrödinger", aliases: ["schrodinger"], category: "Scientist", tier: 3 },
  { answer: "Werner Heisenberg", aliases: ["heisenberg"], category: "Scientist", tier: 3 },
  { answer: "Richard Feynman", aliases: ["feynman"], category: "Scientist", tier: 3 },
  { answer: "James Clerk Maxwell", aliases: ["maxwell", "clerk maxwell"], category: "Scientist", tier: 3 },
  { answer: "Antoine Lavoisier", aliases: ["lavoisier"], category: "Scientist", tier: 3 },
  { answer: "Homer", aliases: ["homer poet"], category: "Author", tier: 3 },
  { answer: "Dante Alighieri", aliases: ["dante"], category: "Author", tier: 3 },
  { answer: "Miguel de Cervantes", aliases: ["cervantes"], category: "Author", tier: 3 },
  { answer: "Charles Dickens", aliases: ["dickens"], category: "Author", tier: 3 },
  { answer: "Mark Twain", aliases: ["twain", "samuel clemens"], category: "Author", tier: 3 },
  { answer: "Jane Austen", aliases: ["austen"], category: "Author", tier: 3 },
  { answer: "Edgar Allan Poe", aliases: ["poe", "edgar allen poe"], category: "Author", tier: 3 },
  { answer: "Franz Kafka", aliases: ["kafka"], category: "Author", tier: 3 },
  { answer: "George Orwell", aliases: ["orwell", "eric blair"], category: "Author", tier: 3 },
  { answer: "Fyodor Dostoevsky", aliases: ["dostoevsky", "dostoyevsky"], category: "Author", tier: 3 },
  { answer: "Leo Tolstoy", aliases: ["tolstoy"], category: "Author", tier: 3 },
  { answer: "Victor Hugo", aliases: ["hugo"], category: "Author", tier: 3 },
  { answer: "J. R. R. Tolkien", aliases: ["tolkien", "jrr tolkien", "j r r tolkien"], category: "Author", tier: 3 },
  { answer: "Johannes Gutenberg", aliases: ["gutenberg"], category: "History", tier: 3 },
  { answer: "Book of Kells", aliases: ["the book of kells"], category: "Book", tier: 3 },
  { answer: "Gutenberg Bible", aliases: ["the gutenberg bible"], category: "Book", tier: 3 },
  { answer: "Rosetta Stone", aliases: ["the rosetta stone"], category: "History", tier: 3 },
  { answer: "Voynich Manuscript", aliases: ["the voynich manuscript"], category: "Book", tier: 3 },
  { answer: "Egyptian Hieroglyphs", aliases: ["hieroglyphics", "hieroglyphs", "hieroglyph"], category: "History", tier: 3 },
  { answer: "Cuneiform", aliases: ["cuneiform writing", "cuneiform script"], category: "History", tier: 3 },
  { answer: "Papyrus", aliases: ["papyrus paper"], category: "History", tier: 3 },
  { answer: "First Folio", aliases: ["the first folio", "shakespeare first folio"], category: "Book", tier: 3 },
  { answer: "Epic of Gilgamesh", aliases: ["gilgamesh", "the epic of gilgamesh"], category: "Book", tier: 3 },
  { answer: "Theremin", aliases: ["theramins"], category: "Music", tier: 3 },
  { answer: "Bagpipes", aliases: ["bagpipe"], category: "Music", tier: 3 },
  { answer: "Didgeridoo", aliases: ["didjeridu"], category: "Music", tier: 3 },
  { answer: "Sitar", aliases: ["sitars"], category: "Music", tier: 3 },
  { answer: "Harmonica", aliases: ["mouth organ", "blues harp"], category: "Music", tier: 3 },
  { answer: "Cello", aliases: ["violoncello"], category: "Music", tier: 3 },
  { answer: "Chopin", aliases: ["frederic chopin"], category: "Composer", tier: 3, wiki: "Frédéric Chopin" },
  { answer: "Tchaikovsky", aliases: ["pyotr ilyich tchaikovsky", "chaikovsky"], category: "Composer", tier: 3, wiki: "Pyotr Ilyich Tchaikovsky" },
  { answer: "Louis Armstrong", aliases: ["satchmo", "louie armstrong"], category: "Person", tier: 3 },
  { answer: "Elvis Presley", aliases: ["elvis"], category: "Person", tier: 3 },
  { answer: "The Birth of Venus", aliases: ["birth of venus", "botticelli venus"], category: "Artwork", tier: 3 },
  { answer: "The Creation of Adam", aliases: ["creation of adam"], category: "Artwork", tier: 3 },
  { answer: "The Last Supper", aliases: ["last supper"], category: "Artwork", tier: 3, wiki: "The Last Supper (Leonardo)" },
  { answer: "The Night Watch", aliases: ["night watch", "the nightwatch", "de nachtwacht"], category: "Artwork", tier: 3 },
  { answer: "Liberty Leading the People", aliases: ["liberty leading people", "delacroix liberty"], category: "Artwork", tier: 3 },
  { answer: "Impression, Sunrise", aliases: ["impression sunrise", "impression soleil levant", "monet sunrise"], category: "Artwork", tier: 3 },
  { answer: "Wanderer above the Sea of Fog", aliases: ["the wanderer above the sea of fog", "wanderer above the mist"], category: "Artwork", tier: 3, wiki: "Wanderer Above the Sea of Fog" },
  { answer: "The Garden of Earthly Delights", aliases: ["garden of earthly delights"], category: "Artwork", tier: 3 },
  { answer: "A Sunday Afternoon on the Island of La Grande Jatte", aliases: ["la grande jatte", "a sunday on la grande jatte", "seurat grande jatte"], category: "Artwork", tier: 3 },
  { answer: "Water Lilies", aliases: ["les nympheas", "monet water lilies", "the water lilies"], category: "Artwork", tier: 3, wiki: "Water Lilies (Monet series)" },
  { answer: "Anubis", aliases: ["anubis god", "anubis egyptian god", "anpu"], category: "Mythology", tier: 3 },
  { answer: "Zeus", aliases: ["jupiter god"], category: "Mythology", tier: 3 },
  { answer: "Thor", aliases: ["thor god", "thor odinson", "donar"], category: "Mythology", tier: 3 },
  { answer: "Odin", aliases: ["woden", "wotan"], category: "Mythology", tier: 3 },
  { answer: "Valkyrie", aliases: ["valkyries", "walkyrie"], category: "Mythology", tier: 3 },
  { answer: "Dragon", aliases: ["dragons"], category: "Mythology", tier: 3 },
  { answer: "Griffin", aliases: ["griffon", "gryphon"], category: "Mythology", tier: 3 },
  { answer: "Phoenix", aliases: ["phoenix bird"], category: "Mythology", tier: 3, wiki: "Phoenix (mythology)" },
  { answer: "Kraken", aliases: ["the kraken"], category: "Mythology", tier: 3 },
  { answer: "Centaur", aliases: ["centaurs"], category: "Mythology", tier: 3 },
  { answer: "Medusa", aliases: ["medusa gorgon", "medusa greek mythology"], category: "Mythology", tier: 3 },
  { answer: "Minotaur", aliases: ["the minotaur"], category: "Mythology", tier: 3 },
  { answer: "Go", aliases: ["go game", "baduk", "weiqi", "igo"], category: "Game", tier: 3, wiki: "Go (game)" },
  { answer: "Mahjong", aliases: ["mah jongg", "mah jong"], category: "Board Game", tier: 3 },
  { answer: "Dungeons & Dragons", aliases: ["dnd", "dungeons and dragons"], category: "Game", tier: 3 },
  { answer: "The Legend of Zelda", aliases: ["zelda", "legend of zelda"], category: "Game", tier: 3 },
  { answer: "Grand Theft Auto", aliases: ["gta", "grand theft auto game", "gta game"], category: "Game", tier: 3 },
  { answer: "Kaleidoscope", aliases: ["kaleidoscopes"], category: "Object", tier: 3 },
  { answer: "Rubber Duck", aliases: ["rubber ducky", "ducky"], category: "Object", tier: 3 },
  { answer: "Paper Clip", aliases: ["paperclip", "paper clips"], category: "Object", tier: 3 },
  { answer: "Zipper", aliases: ["zip", "zip fastener"], category: "Object", tier: 3 },
  { answer: "Velcro", aliases: ["hook and loop"], category: "Object", tier: 3 },
  { answer: "Pocket Watch", aliases: ["pocketwatch"], category: "Object", tier: 3 },
  { answer: "Sextant", aliases: ["sextants"], category: "Object", tier: 3 },
  { answer: "Astrolabe", aliases: ["astrolabes"], category: "Object", tier: 3 },
  { answer: "Abacus", aliases: ["abacuses", "abaci"], category: "Object", tier: 3 },
  { answer: "Jukebox", aliases: ["jukeboxes"], category: "Object", tier: 3 },
  { answer: "Dice", aliases: ["die"], category: "Toy", tier: 3 },
  { answer: "Padlock", aliases: ["padlocks", "lock"], category: "Object", tier: 3 },
  { answer: "Solar Panel", aliases: ["solar panels", "solar cell"], category: "Object", tier: 3 },
  { answer: "Windmill", aliases: ["windmills", "dutch windmill"], category: "Object", tier: 3 },
  { answer: "Lighthouse", aliases: ["lighthouses"], category: "Object", tier: 3 },
  { answer: "Concorde", aliases: ["concord plane", "concorde jet", "the concorde"], category: "Vehicle", tier: 3 },
  { answer: "Model T", aliases: ["ford model t", "model t ford", "tin lizzie"], category: "Vehicle", tier: 3, wiki: "Ford Model T" },
  { answer: "Submarine", aliases: ["submarines", "sub"], category: "Vehicle", tier: 3 },
  { answer: "Steam Locomotive", aliases: ["steam train", "steam engine"], category: "Vehicle", tier: 3 },
  { answer: "Hot Air Balloon", aliases: ["hot air balloons"], category: "Vehicle", tier: 3, wiki: "Hot air balloon" },
  { answer: "Bicycle", aliases: ["bike", "bicycles"], category: "Vehicle", tier: 3 },
  { answer: "Ice Hockey", aliases: ["hockey"], category: "Sport", tier: 3 },
  { answer: "Fencing", aliases: ["sword fighting"], category: "Sport", tier: 3 },
  { answer: "Judo", aliases: ["judo sport", "judoka"], category: "Sport", tier: 3 },
  { answer: "Curling", aliases: ["curling stone"], category: "Sport", tier: 3 },
  { answer: "Figure Skating", aliases: ["iceskating", "ice skating"], category: "Sport", tier: 3 },
  { answer: "Rock Climbing", aliases: ["climbing", "rockclimbing"], category: "Sport", tier: 3 },
  { answer: "Darts", aliases: ["dart", "darts game"], category: "Sport", tier: 3 },
  { answer: "Snooker", aliases: ["snooker table"], category: "Sport", tier: 3 },
  { answer: "Badminton", aliases: ["badminton racket", "shuttlecock"], category: "Sport", tier: 3 },
  { answer: "Playing Cards", aliases: ["deck of cards", "card deck"], category: "Toy", tier: 3 },
  { answer: "Pluto", aliases: ["planet pluto", "dwarf planet pluto"], category: "Space", tier: 3 },
  { answer: "Neptune", aliases: ["planet neptune"], category: "Space", tier: 3 },
  { answer: "Uranus", aliases: ["planet uranus"], category: "Space", tier: 3 },
  { answer: "Europa", aliases: ["europa moon", "jupiter moon", "europa jupiter moon"], category: "Space", tier: 3, wiki: "Europa (moon)" },
  { answer: "Titan", aliases: ["titan moon", "saturn moon", "titan saturn moon"], category: "Space", tier: 3, wiki: "Titan (moon)" },
  { answer: "Orion Nebula", aliases: ["m42", "messier 42", "orion nebula m42"], category: "Space", tier: 3 },
  { answer: "Crab Nebula", aliases: ["m1", "messier 1", "m1 nebula"], category: "Space", tier: 3 },
  { answer: "Black Hole", aliases: ["blackhole", "event horizon"], category: "Space", tier: 3, wiki: "Black hole" },
  { answer: "Halley's Comet", aliases: ["halleys comet", "halley comet"], category: "Space", tier: 3 },
  { answer: "Voyager 1", aliases: ["voyager probe", "voyager spacecraft"], category: "Space", tier: 3 },
  { answer: "James Webb Space Telescope", aliases: ["jwst", "webb telescope", "james webb"], category: "Space", tier: 3 },
  { answer: "Meteorite", aliases: ["meteorites", "meteor"], category: "Space", tier: 3 },
  { answer: "Ostrich", aliases: ["ostriches"], category: "Animal", tier: 3 },
  { answer: "Hedgehog", aliases: ["hedgehogs"], category: "Animal", tier: 3 },
  { answer: "Raccoon", aliases: ["racoon", "racoons", "raccoons"], category: "Animal", tier: 3 },
  { answer: "Beaver", aliases: ["beavers"], category: "Animal", tier: 3 },
  { answer: "Otter", aliases: ["otters"], category: "Animal", tier: 3 },
  { answer: "Llama", aliases: ["llamas"], category: "Animal", tier: 3 },
  { answer: "Snow Leopard", aliases: ["snow leopards", "panthera uncia", "ounce"], category: "Animal", tier: 3 },
  { answer: "Orangutan", aliases: ["orangutang", "orangutans"], category: "Animal", tier: 3 },
  { answer: "Chimpanzee", aliases: ["chimp", "chimps", "chimpanzees"], category: "Animal", tier: 3 },
  { answer: "Lemur", aliases: ["lemurs"], category: "Animal", tier: 3 },
  { answer: "Armadillo", aliases: ["armadillos"], category: "Animal", tier: 3 },
  { answer: "King Cobra", aliases: ["cobra", "cobras"], category: "Animal", tier: 3 },
  { answer: "Alligator", aliases: ["alligators", "gator"], category: "Animal", tier: 3 },
  { answer: "Sea Turtle", aliases: ["seaturtle", "sea turtles", "turtle"], category: "Animal", tier: 3 },
  { answer: "Starfish", aliases: ["star fish", "sea star"], category: "Animal", tier: 3 },
  { answer: "Sea Urchin", aliases: ["sea urchins", "urchin"], category: "Animal", tier: 3 },
  { answer: "Snail", aliases: ["snails"], category: "Animal", tier: 3 },
  { answer: "Fly Agaric", aliases: ["amanita muscaria", "amanita", "toadstool"], category: "Nature", tier: 3, wiki: "Amanita muscaria" },
  { answer: "Giant Sequoia", aliases: ["sequoia", "redwood", "giant redwood"], category: "Plant", tier: 3, wiki: "Sequoiadendron giganteum" },
  { answer: "Lavender", aliases: ["lavandula"], category: "Plant", tier: 3, wiki: "Lavandula" },
  { answer: "Tulip", aliases: ["tulips"], category: "Plant", tier: 3 },
  { answer: "Rose", aliases: ["roses", "rose flower"], category: "Plant", tier: 3 },
  { answer: "Orchid", aliases: ["orchids"], category: "Plant", tier: 3 },
  { answer: "Mushroom", aliases: ["mushrooms", "fungi"], category: "Nature", tier: 3 },
  { answer: "QR Code", aliases: ["qr code", "quick response code", "qrcode"], category: "Tech", tier: 3, wiki: "QR code" },
  { answer: "Barcode", aliases: ["barcodes", "bar code", "upc"], category: "Tech", tier: 3 },
  { answer: "3D Printer", aliases: ["3d printing", "three d printer"], category: "Tech", tier: 3, wiki: "3D printing" },
  { answer: "Drone", aliases: ["drones", "uav", "unmanned aerial vehicle", "quadcopter"], category: "Tech", tier: 3, wiki: "Unmanned aerial vehicle" },
  { answer: "Motherboard", aliases: ["mainboard", "logic board", "mobo"], category: "Tech", tier: 3 },
  { answer: "USB Flash Drive", aliases: ["usb stick", "usb drive", "thumb drive", "memory stick", "pen drive"], category: "Tech", tier: 3 },
  { answer: "Hard Disk Drive", aliases: ["hard drive", "hard disk", "hdd"], category: "Tech", tier: 3 },
  { answer: "Microprocessor", aliases: ["cpu", "processor", "micro chip", "microchip"], category: "Tech", tier: 3 },
  { answer: "MRI Machine", aliases: ["mri", "magnetic resonance imaging", "mri scanner"], category: "Medicine", tier: 3, wiki: "Magnetic resonance imaging" },
  { answer: "Penicillin", aliases: ["penicillium", "penicillin mold"], category: "Medicine", tier: 3 },
  { answer: "Vaccine", aliases: ["vaccination", "vaccines"], category: "Medicine", tier: 3, wiki: "Vaccination" },

  { type: "text", mode: "math", answer: "56", category: "Math", tier: 1, text: "7 × 8 = ?" },
  { type: "text", mode: "math", answer: "42", category: "Math", tier: 1, text: "6 × 7 = ?" },
  { type: "text", mode: "math", answer: "66", category: "Math", tier: 1, text: "100 − 34 = ?" },
  { type: "text", mode: "math", answer: "35", category: "Math", tier: 1, text: "9 + 26 = ?" },
  { type: "text", mode: "math", answer: "48", category: "Math", tier: 1, text: "Half of 96 = ?" },
  { type: "text", mode: "math", answer: "36", category: "Math", tier: 1, text: "6² = ?" },
  { type: "text", mode: "math", answer: "9", category: "Math", tier: 1, text: "√81 = ?" },
  { type: "text", mode: "math", answer: "30", category: "Math", tier: 1, text: "15% of 200 = ?" },
  { type: "text", mode: "math", answer: "100", category: "Math", tier: 1, text: "25 × 4 = ?" },
  { type: "text", mode: "math", answer: "23", category: "Math", tier: 1, text: "3 + 4 × 5 = ?" },
  { type: "text", mode: "math", answer: "156", category: "Math", tier: 2, text: "13 × 12 = ?" },
  { type: "text", mode: "math", answer: "13", category: "Math", tier: 2, text: "√169 = ?" },
  { type: "text", mode: "math", answer: "81", category: "Math", tier: 2, text: "3⁴ = ?" },
  { type: "text", mode: "math", answer: "20", category: "Math", tier: 2, text: "25% of 80 = ?" },
  { type: "text", mode: "math", answer: "7", category: "Math", tier: 2, text: "2x + 3 = 17  →  x = ?" },
  { type: "text", mode: "math", answer: "162", category: "Math", tier: 2, text: "2, 6, 18, 54, … = ?" },
  { type: "text", mode: "math", answer: "14", category: "Math", tier: 2, text: "1² + 2² + 3² = ?" },
  { type: "text", mode: "math", answer: "49", category: "Math", tier: 2, text: "10² − 51 = ?" },
  { type: "text", mode: "math", answer: "437", category: "Math", tier: 3, text: "19 × 23 = ?" },
  { type: "text", mode: "math", answer: "17", category: "Math", tier: 3, text: "√289 = ?" },
  { type: "text", mode: "math", answer: "1024", category: "Math", tier: 3, text: "2¹⁰ = ?" },
  { type: "text", mode: "math", answer: "5040", category: "Math", tier: 3, text: "7! = ?" },
  { type: "text", mode: "math", answer: "210", category: "Math", tier: 3, text: "1 + 2 + … + 20 = ?" },
  { type: "text", mode: "math", answer: "89", category: "Math", tier: 3, text: "Next Fibonacci number after 55 = ?" },

  { type: "text", answer: "question", category: "Quote", tier: 1, text: "To be, or not to be, that is the ______", desc: "Hamlet, Shakespeare" },
  { type: "text", answer: "mankind", category: "Quote", tier: 1, text: "That's one small step for man, one giant leap for ______", desc: "Neil Armstrong, 1969" },
  { type: "text", answer: "with you", category: "Quote", tier: 1, text: "May the Force be ______", desc: "Star Wars" },
  { type: "text", answer: "problem", category: "Quote", tier: 1, text: "Houston, we have a ______", desc: "Apollo 13" },
  { type: "text", answer: "back", category: "Quote", tier: 1, text: "I'll be ______", desc: "The Terminator" },
  { type: "text", answer: "watson", category: "Quote", tier: 1, text: "Elementary, my dear ______", desc: "Sherlock Holmes" },
  { type: "text", answer: "truth", category: "Quote", tier: 1, text: "You can't handle the ______", desc: "A Few Good Men" },
  { type: "text", answer: "and beyond", category: "Quote", tier: 1, text: "To infinity ______", desc: "Toy Story" },
  { type: "text", answer: "chocolates", category: "Quote", tier: 1, text: "Life is like a box of ______", desc: "Forrest Gump" },
  { type: "text", answer: "coming", category: "Quote", tier: 1, text: "Winter is ______", desc: "Game of Thrones" },
  { type: "text", answer: "conquered", category: "Quote", tier: 2, text: "Veni, vidi, vici — I came, I saw, I ______", desc: "Julius Caesar" },
  { type: "text", answer: "bee", category: "Quote", tier: 2, text: "Float like a butterfly, sting like a ______", desc: "Muhammad Ali" },
  { type: "text", answer: "sword", category: "Quote", tier: 2, text: "The pen is mightier than the ______", desc: "Edward Bulwer-Lytton" },
  { type: "text", answer: "country", category: "Quote", tier: 2, text: "Ask not what your country can do for you — ask what you can do for your ______", desc: "John F. Kennedy, 1961" },
  { type: "text", answer: "perspiration", category: "Quote", tier: 2, text: "Genius is one percent inspiration, ninety-nine percent ______", desc: "Thomas Edison" },
  { type: "text", answer: "stick", category: "Quote", tier: 2, text: "Speak softly and carry a big ______", desc: "Theodore Roosevelt" },
  { type: "text", answer: "step", category: "Quote", tier: 2, text: "A journey of a thousand miles begins with a single ______", desc: "Lao Tzu" },
  { type: "text", answer: "stronger", category: "Quote", tier: 2, text: "That which does not kill us makes us ______", desc: "Friedrich Nietzsche" },
  { type: "text", answer: "vici", category: "Quote", tier: 3, text: "Veni, vidi, ______", desc: "Julius Caesar" },
  { type: "text", answer: "sum", category: "Quote", tier: 3, text: "Cogito, ergo ______", desc: "René Descartes" },
  { type: "text", answer: "diem", category: "Quote", tier: 3, text: "Carpe ______", desc: "Horace" },
  { type: "text", answer: "brute", category: "Quote", tier: 3, text: "Et tu, ______?", desc: "Shakespeare, Julius Caesar" },
  { type: "text", answer: "living", category: "Quote", tier: 3, text: "The unexamined life is not worth ______", desc: "Socrates" },
  { type: "text", answer: "mori", category: "Quote", tier: 3, text: "Memento ______", desc: "Latin phrase" },

  { type: "text", mode: "quiz", answer: "1945", category: "History", tier: 1, text: "World War II ended in which year?" },
  { type: "text", mode: "quiz", answer: "1989", category: "History", tier: 1, text: "The Berlin Wall fell in which year?" },
  { type: "text", mode: "quiz", answer: "1969", category: "History", tier: 1, text: "Humans first walked on the Moon in which year?" },
  { type: "text", mode: "quiz", answer: "1912", category: "History", tier: 1, text: "The Titanic sank in which year?" },
  { type: "text", mode: "quiz", answer: "1914", category: "History", tier: 1, text: "World War I began in which year?" },
  { type: "text", mode: "quiz", answer: "1789", category: "History", tier: 1, text: "The French Revolution began in which year?" },
  { type: "text", mode: "quiz", answer: "1945", category: "History", tier: 1, text: "The atomic bomb was dropped on Hiroshima in which year?" },
  { type: "text", mode: "quiz", answer: "1991", category: "History", tier: 1, text: "The Soviet Union dissolved, ending the Cold War, in which year?" },
  { type: "text", mode: "quiz", answer: "1492", category: "History", tier: 2, text: "Christopher Columbus reached the Americas in which year?" },
  { type: "text", mode: "quiz", answer: "1776", category: "History", tier: 2, text: "The US Declaration of Independence was signed in which year?" },
  { type: "text", mode: "quiz", answer: "1815", category: "History", tier: 2, text: "Napoleon lost the Battle of Waterloo in which year?" },
  { type: "text", mode: "quiz", answer: "1896", category: "History", tier: 2, text: "The first modern Olympic Games were held in which year?" },
  { type: "text", mode: "quiz", answer: "1917", category: "History", tier: 2, text: "The Russian Revolution began in which year?" },
  { type: "text", mode: "quiz", answer: "1963", category: "History", tier: 2, text: "John F. Kennedy was assassinated in which year?" },
  { type: "text", mode: "quiz", answer: "1975", category: "History", tier: 2, text: "The Vietnam War ended with the fall of Saigon in which year?" },
  { type: "text", mode: "quiz", answer: "1994", category: "History", tier: 2, text: "Nelson Mandela became South Africa's president in which year?" },
  { type: "text", mode: "quiz", answer: "476", category: "History", tier: 3, text: "The Western Roman Empire fell in which year?" },
  { type: "text", mode: "quiz", answer: "1347", category: "History", tier: 3, text: "The Black Death reached Europe in which year?" },
  { type: "text", mode: "quiz", answer: "1215", category: "History", tier: 3, text: "The Magna Carta was sealed in which year?" },
  { type: "text", mode: "quiz", answer: "1453", category: "History", tier: 3, text: "Constantinople fell to the Ottomans in which year?" },
  { type: "text", mode: "quiz", answer: "1919", category: "History", tier: 3, text: "The Treaty of Versailles was signed in which year?" },
  { type: "text", mode: "quiz", answer: "1957", category: "History", tier: 3, text: "Sputnik 1 was launched in which year?" },
  { type: "text", mode: "quiz", answer: "1986", category: "History", tier: 3, text: "The Chernobyl disaster happened in which year?" },

  { answer: "Japan", aliases: ["japan flag", "japanese flag", "nippon"], category: "Geography", tier: 2, wiki: "Flag of Japan" },
  { answer: "France", aliases: ["french flag"], category: "Geography", tier: 2, wiki: "Flag of France" },
  { answer: "Germany", aliases: ["german flag"], category: "Geography", tier: 2, wiki: "Flag of Germany" },
  { answer: "Italy", aliases: ["italian flag"], category: "Geography", tier: 2, wiki: "Flag of Italy" },
  { answer: "Spain", aliases: ["spanish flag"], category: "Geography", tier: 2, wiki: "Flag of Spain" },
  { answer: "Portugal", aliases: ["portuguese flag"], category: "Geography", tier: 2, wiki: "Flag of Portugal" },
  { answer: "Netherlands", aliases: ["holland", "dutch flag"], category: "Geography", tier: 2, wiki: "Flag of the Netherlands" },
  { answer: "Sweden", aliases: ["swedish flag"], category: "Geography", tier: 2, wiki: "Flag of Sweden" },
  { answer: "Greece", aliases: ["greek flag"], category: "Geography", tier: 2, wiki: "Flag of Greece" },
  { answer: "Switzerland", aliases: ["swiss flag"], category: "Geography", tier: 2, wiki: "Flag of Switzerland" },
  { answer: "United Kingdom", aliases: ["uk", "great britain", "britain", "england", "union jack"], category: "Geography", tier: 2, wiki: "Flag of the United Kingdom" },
  { answer: "United States", aliases: ["usa", "us", "america", "united states of america"], category: "Geography", tier: 2, wiki: "Flag of the United States" },
  { answer: "Canada", aliases: ["canadian flag"], category: "Geography", tier: 2, wiki: "Flag of Canada" },
  { answer: "Mexico", aliases: ["mexican flag"], category: "Geography", tier: 2, wiki: "Flag of Mexico" },
  { answer: "Brazil", aliases: ["brazilian flag"], category: "Geography", tier: 2, wiki: "Flag of Brazil" },
  { answer: "Argentina", aliases: ["argentinian flag", "argentine flag"], category: "Geography", tier: 2, wiki: "Flag of Argentina" },
  { answer: "India", aliases: ["indian flag"], category: "Geography", tier: 2, wiki: "Flag of India" },
  { answer: "China", aliases: ["chinese flag", "peoples republic of china"], category: "Geography", tier: 2, wiki: "Flag of China" },
  { answer: "South Korea", aliases: ["republic of korea", "korea", "korean flag"], category: "Geography", tier: 2, wiki: "Flag of South Korea" },
  { answer: "Ukraine", aliases: ["ukrainian flag"], category: "Geography", tier: 2, wiki: "Flag of Ukraine" },

  { answer: "Nile", aliases: ["the nile", "nile river", "the nile river"], category: "Geography", tier: 2, wiki: "Nile" },
  { answer: "Amazon River", aliases: ["the amazon river"], category: "Geography", tier: 2, wiki: "Amazon River" },
  { answer: "Mount Kilimanjaro", aliases: ["kilimanjaro"], category: "Geography", tier: 2, wiki: "Mount Kilimanjaro" },
  { answer: "Mont Blanc", aliases: ["monte bianco", "mont blanc mountain", "white mountain"], category: "Geography", tier: 2, wiki: "Mont Blanc" },
  { answer: "Matterhorn", aliases: ["the matterhorn"], category: "Geography", tier: 2, wiki: "Matterhorn" },
  { answer: "Mount Rushmore", aliases: ["rushmore"], category: "Geography", tier: 2, wiki: "Mount Rushmore" },
  { answer: "Venice", aliases: ["venezia", "venice italy"], category: "Geography", tier: 2, wiki: "Venice" },
  { answer: "Burj Khalifa", aliases: ["burj khalifa tower", "khalifa tower", "burj dubai"], category: "Geography", tier: 2, wiki: "Burj Khalifa" },
  { answer: "Golden Gate Bridge", aliases: ["the golden gate bridge"], category: "Geography", tier: 2, wiki: "Golden Gate Bridge" },
  { answer: "Brooklyn Bridge", aliases: ["the brooklyn bridge"], category: "Geography", tier: 2, wiki: "Brooklyn Bridge" },
  { answer: "Tower Bridge", aliases: ["the tower bridge", "tower bridge london"], category: "Geography", tier: 2, wiki: "Tower Bridge" },
  { answer: "Panama Canal", aliases: ["the panama canal"], category: "Geography", tier: 2, wiki: "Panama Canal" },
  { answer: "Suez Canal", aliases: ["the suez canal"], category: "Geography", tier: 2, wiki: "Suez Canal" },
  { answer: "Brandenburg Gate", aliases: ["the brandenburg gate"], category: "Geography", tier: 2, wiki: "Brandenburg Gate" },
  { answer: "Arc de Triomphe", aliases: ["the arc de triomphe"], category: "Geography", tier: 2, wiki: "Arc de Triomphe" },
  { answer: "Louvre", aliases: ["the louvre", "louvre museum", "the louvre museum"], category: "Geography", tier: 2, wiki: "Louvre" },
  { answer: "Buckingham Palace", aliases: ["buckingham palace london", "buck house"], category: "Geography", tier: 2, wiki: "Buckingham Palace" },
  { answer: "White House", aliases: ["the white house"], category: "Geography", tier: 2, wiki: "White House" },
  { answer: "Mount Vesuvius", aliases: ["vesuvius"], category: "Geography", tier: 2, wiki: "Mount Vesuvius" },
  { answer: "Krakatoa", aliases: ["krakatau"], category: "Geography", tier: 2, wiki: "Krakatoa" },
  { answer: "Dead Sea", aliases: ["the dead sea"], category: "Geography", tier: 2, wiki: "Dead Sea" },
  { answer: "Santorini", aliases: ["santorini greece", "thera", "santorini island"], category: "Geography", tier: 2, wiki: "Santorini" },
  { answer: "Iguazu Falls", aliases: ["iguazu", "iguacu falls", "iguassu falls"], category: "Geography", tier: 2, wiki: "Iguazu Falls" },
  { answer: "Angel Falls", aliases: ["the angel falls"], category: "Geography", tier: 2, wiki: "Angel Falls" },
  { answer: "Easter Island", aliases: ["rapa nui"], category: "Geography", tier: 2, wiki: "Easter Island" },
  { answer: "Thames", aliases: ["river thames", "the thames"], category: "Geography", tier: 2, wiki: "River Thames" },
  { answer: "Sydney Harbour Bridge", aliases: ["the sydney harbour bridge"], category: "Geography", tier: 2, wiki: "Sydney Harbour Bridge" },
  { answer: "Patagonia", aliases: ["patagonia region", "patagonia argentina"], category: "Geography", tier: 2, wiki: "Patagonia" },
  { answer: "K2", aliases: ["mount godwin austen"], category: "Geography", tier: 3, wiki: "K2" },
  { answer: "Gobi Desert", aliases: ["the gobi desert", "the gobi", "gobi"], category: "Geography", tier: 3, wiki: "Gobi Desert" },
  { answer: "Serengeti", aliases: ["the serengeti"], category: "Geography", tier: 3, wiki: "Serengeti" },
  { answer: "Danube", aliases: ["the danube", "danube river"], category: "Geography", tier: 3, wiki: "Danube" },
  { answer: "Lake Baikal", aliases: ["baikal"], category: "Geography", tier: 3, wiki: "Lake Baikal" },
  { answer: "Cape of Good Hope", aliases: ["the cape of good hope"], category: "Geography", tier: 3, wiki: "Cape of Good Hope" },
  { answer: "Himeji Castle", aliases: ["himeji"], category: "Geography", tier: 3, wiki: "Himeji Castle" },
  { answer: "Petronas Towers", aliases: ["petronas twin towers", "the petronas towers"], category: "Geography", tier: 3, wiki: "Petronas Towers" },
  { answer: "Table Mountain", aliases: ["the table mountain"], category: "Geography", tier: 3, wiki: "Table Mountain" },
  { answer: "Bora Bora", aliases: ["bora bora island", "bora-bora"], category: "Geography", tier: 3, wiki: "Bora Bora" },
  { answer: "Ha Long Bay", aliases: ["halong bay", "the ha long bay"], category: "Geography", tier: 3, wiki: "Ha Long Bay" },
  { answer: "Denali", aliases: ["mount mckinley", "mckinley", "mt mckinley"], category: "Geography", tier: 3, wiki: "Denali" },
  { answer: "Rock of Gibraltar", aliases: ["gibraltar", "the rock of gibraltar"], category: "Geography", tier: 3, wiki: "Rock of Gibraltar" },

  { answer: "Enigma Machine", aliases: ["enigma", "the enigma machine", "enigma code machine"], category: "History", tier: 2, wiki: "Enigma machine" },
  { answer: "Berlin Wall", aliases: ["the berlin wall"], category: "History", tier: 2, wiki: "Berlin Wall" },
  { answer: "Bayeux Tapestry", aliases: ["the bayeux tapestry"], category: "History", tier: 2, wiki: "Bayeux Tapestry" },
  { answer: "Magna Carta", aliases: ["the magna carta"], category: "History", tier: 2, wiki: "Magna Carta" },
  { answer: "Hindenburg", aliases: ["the hindenburg", "hindenburg disaster", "lz 129 hindenburg"], category: "History", tier: 2, wiki: "LZ 129 Hindenburg" },
  { answer: "Trinity Test", aliases: ["trinity nuclear test", "the trinity test", "first nuclear test"], category: "History", tier: 2, wiki: "Trinity (nuclear test)" },
  { answer: "Chernobyl Disaster", aliases: ["chernobyl", "the chernobyl disaster"], category: "History", tier: 2, wiki: "Chernobyl disaster" },
  { answer: "Winston Churchill", aliases: ["churchill"], category: "History", tier: 2, wiki: "Winston Churchill" },
  { answer: "Joan of Arc", aliases: ["jeanne darc"], category: "History", tier: 2, wiki: "Joan of Arc" },
  { answer: "Genghis Khan", aliases: ["temujin"], category: "History", tier: 2, wiki: "Genghis Khan" },
  { answer: "Alexander the Great", aliases: ["alexander"], category: "History", tier: 2, wiki: "Alexander the Great" },
  { answer: "Samurai", aliases: ["samurai warrior", "samurais"], category: "History", tier: 2, wiki: "Samurai" },
  { answer: "Vikings", aliases: ["viking"], category: "History", tier: 2, wiki: "Vikings" },
  { answer: "Aztecs", aliases: ["aztec", "the aztecs"], category: "History", tier: 2, wiki: "Aztecs" },
  { answer: "Maya Civilization", aliases: ["the maya", "maya", "mayans", "mayan", "the mayans"], category: "History", tier: 2, wiki: "Maya civilization" },
  { answer: "Inca Empire", aliases: ["inca", "the incas", "incas", "the inca empire"], category: "History", tier: 2, wiki: "Inca Empire" },
  { answer: "Roman Empire", aliases: ["the roman empire"], category: "History", tier: 2, wiki: "Roman Empire" },
  { answer: "Ancient Egypt", aliases: ["ancient egyptian civilization", "kemet"], category: "History", tier: 2, wiki: "Ancient Egypt" },
  { answer: "Mongol Empire", aliases: ["the mongol empire", "mongols", "the mongols"], category: "History", tier: 2, wiki: "Mongol Empire" },
  { answer: "Ottoman Empire", aliases: ["the ottoman empire"], category: "History", tier: 2, wiki: "Ottoman Empire" },
  { answer: "Industrial Revolution", aliases: ["the industrial revolution"], category: "History", tier: 2, wiki: "Industrial Revolution" },
  { answer: "Renaissance", aliases: ["the renaissance"], category: "History", tier: 2, wiki: "Renaissance" },
  { answer: "Middle Ages", aliases: ["the middle ages", "medieval", "medieval times", "medieval period"], category: "History", tier: 2, wiki: "Middle Ages" },
  { answer: "Silk Road", aliases: ["the silk road"], category: "History", tier: 2, wiki: "Silk Road" },
  { answer: "Wright Brothers", aliases: ["the wright brothers", "orville and wilbur wright"], category: "History", tier: 2, wiki: "Wright brothers" },
  { answer: "V-2 Rocket", aliases: ["v2 rocket", "v2", "the v-2 rocket"], category: "History", tier: 2, wiki: "V-2 rocket" },
  { answer: "Sutton Hoo Helmet", aliases: ["sutton hoo", "the sutton hoo helmet"], category: "History", tier: 3, wiki: "Sutton Hoo helmet" },
  { answer: "Hiroshima Peace Memorial", aliases: ["genbaku dome", "a-bomb dome", "atomic bomb dome", "the hiroshima peace memorial"], category: "History", tier: 3, wiki: "Hiroshima Peace Memorial (Genbaku Dome)" },
  { answer: "Plato", aliases: ["plato philosopher", "platon"], category: "History", tier: 3, wiki: "Plato" },
  { answer: "Socrates", aliases: ["sokrates", "socrates philosopher"], category: "History", tier: 3, wiki: "Socrates" },
  { answer: "Aristotle", aliases: ["aristoteles", "aristotle philosopher"], category: "History", tier: 3, wiki: "Aristotle" },
  { answer: "Archimedes", aliases: ["archimedes principle"], category: "History", tier: 3, wiki: "Archimedes" },
  { answer: "Pythagoras", aliases: ["pythagoras theorem", "pythagore"], category: "History", tier: 3, wiki: "Pythagoras" },
  { answer: "Confucius", aliases: ["kong fuzi", "kongzi"], category: "History", tier: 3, wiki: "Confucius" },
  { answer: "Gautama Buddha", aliases: ["buddha", "the buddha"], category: "History", tier: 3, wiki: "Gautama Buddha" },
  { answer: "Ramesses II", aliases: ["ramses ii", "ramses the great", "rameses ii"], category: "History", tier: 3, wiki: "Ramesses II" },
  { answer: "Hatshepsut", aliases: ["hatshepsut queen", "hatshepsowe"], category: "History", tier: 3, wiki: "Hatshepsut" },
  { answer: "Cyrus the Great", aliases: ["cyrus"], category: "History", tier: 3, wiki: "Cyrus the Great" },
  { answer: "Simón Bolívar", aliases: ["simon bolivar", "bolivar"], category: "History", tier: 3, wiki: "Simón Bolívar" },
  { answer: "Pony Express", aliases: ["the pony express"], category: "History", tier: 3, wiki: "Pony Express" },

  { answer: "Pong", aliases: ["pong game", "pong arcade"], category: "Game", tier: 2, wiki: "Pong" },
  { answer: "Space Invaders", aliases: ["space invader", "space invaders arcade"], category: "Game", tier: 2, wiki: "Space Invaders" },
  { answer: "Donkey Kong", aliases: ["donkey kong arcade"], category: "Game", tier: 2, wiki: "Donkey Kong (arcade game)" },
  { answer: "Atari 2600", aliases: ["atari"], category: "Game", tier: 2, wiki: "Atari 2600" },
  { answer: "Game Boy", aliases: ["gameboy", "the game boy"], category: "Game", tier: 2, wiki: "Game Boy" },
  { answer: "Nintendo 64", aliases: ["n64"], category: "Game", tier: 2, wiki: "Nintendo 64" },
  { answer: "Tamagotchi", aliases: ["tamagotchis"], category: "Game", tier: 2, wiki: "Tamagotchi" },
  { answer: "Scrabble", aliases: ["scrabble game", "scrabble board game"], category: "Game", tier: 2, wiki: "Scrabble" },
  { answer: "Uno", aliases: ["uno card game"], category: "Game", tier: 2, wiki: "Uno (card game)" },
  { answer: "Monopoly", aliases: ["monopoly board game"], category: "Game", tier: 2, wiki: "Monopoly (game)" },
  { answer: "Roblox", aliases: ["roblox game"], category: "Game", tier: 2, wiki: "Roblox" },
  { answer: "Counter-Strike", aliases: ["counter strike", "cs"], category: "Game", tier: 2, wiki: "Counter-Strike" },
  { answer: "Sudoku", aliases: ["sudoku puzzle", "sudoku game"], category: "Game", tier: 2, wiki: "Sudoku" },
  { answer: "Kite", aliases: ["kites", "kite flying"], category: "Game", tier: 2, wiki: "Kite" },
  { answer: "Frisbee", aliases: ["flying disc", "flying discs"], category: "Game", tier: 2, wiki: "Flying discs" },
  { answer: "Game & Watch", aliases: ["game and watch"], category: "Game", tier: 3, wiki: "Game & Watch" },
  { answer: "Commodore 64", aliases: ["c64", "commodore"], category: "Game", tier: 3, wiki: "Commodore 64" },
  { answer: "Arcade Cabinet", aliases: ["arcade machine", "the arcade cabinet"], category: "Game", tier: 3, wiki: "Arcade cabinet" },
  { answer: "Joystick", aliases: ["joysticks"], category: "Game", tier: 3, wiki: "Joystick" },
  { answer: "Virtual Boy", aliases: ["the virtual boy"], category: "Game", tier: 3, wiki: "Virtual Boy" },
  { answer: "Foosball", aliases: ["table football", "table soccer"], category: "Game", tier: 3, wiki: "Foosball" },
  { answer: "Air Hockey", aliases: ["airhockey"], category: "Game", tier: 3, wiki: "Air hockey" },
  { answer: "Dodgeball", aliases: ["dodge ball", "dodgeball game"], category: "Game", tier: 3, wiki: "Dodgeball" },
  { answer: "Magic: The Gathering", aliases: ["mtg", "magic the gathering"], category: "Game", tier: 3, wiki: "Magic: The Gathering" },
  { answer: "Hot Wheels", aliases: ["hotwheels"], category: "Game", tier: 3, wiki: "Hot Wheels" },
  { answer: "Hula Hoop", aliases: ["hula hoops"], category: "Game", tier: 3, wiki: "Hula hoop" },
  { answer: "Trampoline", aliases: ["trampolines"], category: "Game", tier: 3, wiki: "Trampoline" },
  { answer: "Pogo Stick", aliases: ["pogostick"], category: "Game", tier: 3, wiki: "Pogo stick" },
  { answer: "Model Railway", aliases: ["model train", "model trains", "model railroad"], category: "Game", tier: 3, wiki: "Model railway" },
  { answer: "Crossword", aliases: ["crossword puzzle", "crosswords"], category: "Game", tier: 3, wiki: "Crossword" },

  // === EXPANSION PACK — 180+ new subjects across new categories ===
  // Fashion
  { answer: "Kimono", aliases: ["kimonos", "japanese kimono"], category: "Fashion", tier: 2, wiki: "Kimono" },
  { answer: "Sari", aliases: ["saree"], category: "Fashion", tier: 2, wiki: "Sari" },
  { answer: "Beret", aliases: ["berets", "french beret"], category: "Fashion", tier: 2, wiki: "Beret" },
  { answer: "Tuxedo", aliases: ["tux"], category: "Fashion", tier: 2, wiki: "Tuxedo" },
  { answer: "High Heels", aliases: ["stilettos", "stiletto heels"], category: "Fashion", tier: 2, wiki: "High-heeled shoe" },
  { answer: "Fedora", aliases: ["fedora hat"], category: "Fashion", tier: 2, wiki: "Fedora" },
  { answer: "Kilts", aliases: ["kilt"], category: "Fashion", tier: 2, wiki: "Kilt" },
  { answer: "Leather Jacket", aliases: ["biker jacket"], category: "Fashion", tier: 2, wiki: "Leather jacket" },
  { answer: "Polo Shirt", aliases: ["polo"], category: "Fashion", tier: 2, wiki: "Polo shirt" },
  { answer: "Bikini", aliases: ["bikinis", "bikini swimsuit"], category: "Fashion", tier: 2, wiki: "Bikini" },
  { answer: "Hanbok", aliases: ["hanboks", "korean hanbok"], category: "Fashion", tier: 3, wiki: "Hanbok" },
  { answer: "Dirndl", aliases: ["dirndls", "german dirndl"], category: "Fashion", tier: 3, wiki: "Dirndl" },
  { answer: "Sombrero", aliases: ["sombreros", "mexican sombrero"], category: "Fashion", tier: 3, wiki: "Sombrero" },
  { answer: "Turban", aliases: ["turbans", "dastar"], category: "Fashion", tier: 3, wiki: "Turban" },
  { answer: "Yukata", aliases: ["yukatas", "japanese yukata"], category: "Fashion", tier: 3, wiki: "Yukata" },

  // Architecture
  { answer: "Fallingwater", aliases: ["falling water house"], category: "Architecture", tier: 2, wiki: "Fallingwater" },
  { answer: "Guggenheim Museum", aliases: ["guggenheim", "solomon guggenheim museum"], category: "Architecture", tier: 2, wiki: "Solomon R. Guggenheim Museum" },
  { answer: "Burj Al Arab", aliases: ["burj al arab hotel"], category: "Architecture", tier: 2, wiki: "Burj Al Arab" },
  { answer: "Pantheon", aliases: ["the pantheon", "pantheon rome"], category: "Architecture", tier: 2, wiki: "Pantheon, Rome" },
  { answer: "Sydney Opera House", aliases: ["sydney opera", "opera house"], category: "Architecture", tier: 2, wiki: "Sydney Opera House" },
  { answer: "Big Ben", aliases: ["elizabeth tower", "the elizabeth tower", "big ben tower"], category: "Architecture", tier: 2, wiki: "Big Ben" },
  { answer: "Gaudi Casa Batllo", aliases: ["casa batllo", "casa batlló"], category: "Architecture", tier: 3, wiki: "Casa Batlló" },
  { answer: "Pagoda", aliases: ["pagodas"], category: "Architecture", tier: 3, wiki: "Pagoda" },
  { answer: "Stave Church", aliases: ["norwegian stave church"], category: "Architecture", tier: 3, wiki: "Stave church" },
  { answer: "Ziggurat", aliases: ["ziggurats"], category: "Architecture", tier: 3, wiki: "Ziggurat" },

  // Cinema
  { answer: "The Godfather", aliases: ["godfather"], category: "Cinema", tier: 2, wiki: "The Godfather" },
  { answer: "Citizen Kane", aliases: ["citizen kane film", "rosebud film"], category: "Cinema", tier: 2, wiki: "Citizen Kane" },
  { answer: "Casablanca", aliases: ["casablanca film"], category: "Cinema", tier: 2, wiki: "Casablanca (film)" },
  { answer: "Star Wars", aliases: ["star wars film", "a new hope", "star wars franchise", "star wars saga"], category: "Cinema", tier: 2, wiki: "Star Wars (film)" },
  { answer: "Titanic", aliases: ["titanic film", "titanic 1997"], category: "Cinema", tier: 2, wiki: "Titanic (1997 film)" },
  { answer: "The Shawshank Redemption", aliases: ["shawshank redemption", "shawshank"], category: "Cinema", tier: 2, wiki: "The Shawshank Redemption" },
  { answer: "Pulp Fiction", aliases: ["pulp fiction film", "quentin tarantino pulp fiction"], category: "Cinema", tier: 2, wiki: "Pulp Fiction" },
  { answer: "Jurassic Park", aliases: ["jurassic park film", "jurassic park movie", "jp"], category: "Cinema", tier: 2, wiki: "Jurassic Park (film)" },
  { answer: "Avatar", aliases: ["avatar film", "avatar 2009"], category: "Cinema", tier: 2, wiki: "Avatar (2009 film)" },
  { answer: "The Matrix", aliases: ["matrix film"], category: "Cinema", tier: 2, wiki: "The Matrix" },
  { answer: "Psycho", aliases: ["psycho film", "psycho hitchcock"], category: "Cinema", tier: 3, wiki: "Psycho (1960 film)" },
  { answer: "Metropolis", aliases: ["metropolis film", "metropolis 1927"], category: "Cinema", tier: 3, wiki: "Metropolis (1927 film)" },
  { answer: "Gone with the Wind", aliases: ["gone with the wind film", "gwtw"], category: "Cinema", tier: 3, wiki: "Gone with the Wind (film)" },
  { answer: "Spirited Away", aliases: ["sen to chihiro"], category: "Cinema", tier: 3, wiki: "Spirited Away" },

  // TV Show
  { answer: "Breaking Bad", aliases: ["breaking bad tv", "breaking bad series", "bb"], category: "TV Show", tier: 2, wiki: "Breaking Bad" },
  { answer: "Friends", aliases: ["friends tv show"], category: "TV Show", tier: 2, wiki: "Friends" },
  { answer: "Game of Thrones", aliases: ["got"], category: "TV Show", tier: 2, wiki: "Game of Thrones" },
  { answer: "The Simpsons", aliases: ["simpsons"], category: "TV Show", tier: 2, wiki: "The Simpsons" },
  { answer: "Stranger Things", aliases: ["stranger things tv", "stranger things series"], category: "TV Show", tier: 2, wiki: "Stranger Things" },
  { answer: "Sherlock", aliases: ["sherlock bbc"], category: "TV Show", tier: 2, wiki: "Sherlock (TV series)" },
  { answer: "Doctor Who", aliases: ["dr who"], category: "TV Show", tier: 3, wiki: "Doctor Who" },
  { answer: "Twin Peaks", aliases: ["twin peaks tv"], category: "TV Show", tier: 3, wiki: "Twin Peaks" },
  { answer: "Seinfeld", aliases: ["seinfeld tv show", "seinfeld series"], category: "TV Show", tier: 3, wiki: "Seinfeld" },
  { answer: "The Office", aliases: ["the office us", "the office american"], category: "TV Show", tier: 3, wiki: "The Office (American TV series)" },

  // Cartoon
  { answer: "Mickey Mouse", aliases: ["mickey"], category: "Cartoon", tier: 2, wiki: "Mickey Mouse" },
  { answer: "Bugs Bunny", aliases: ["bugs bunny"], category: "Cartoon", tier: 2, wiki: "Bugs Bunny" },
  { answer: "SpongeBob SquarePants", aliases: ["spongebob", "sponge bob"], category: "Cartoon", tier: 2, wiki: "SpongeBob SquarePants" },
  { answer: "Scooby-Doo", aliases: ["scooby doo", "scooby"], category: "Cartoon", tier: 2, wiki: "Scooby-Doo" },
  { answer: "Tom and Jerry", aliases: ["tom & jerry"], category: "Cartoon", tier: 2, wiki: "Tom and Jerry" },
  { answer: "The Flintstones", aliases: ["flintstones"], category: "Cartoon", tier: 3, wiki: "The Flintstones" },
  { answer: "Peppa Pig", aliases: ["peppa"], category: "Cartoon", tier: 3, wiki: "Peppa Pig" },
  { answer: "Garfield", aliases: ["garfield cat", "garfield cartoon"], category: "Cartoon", tier: 3, wiki: "Garfield" },
  { answer: "Doraemon", aliases: ["doraemon cat", "doraemon anime"], category: "Cartoon", tier: 3, wiki: "Doraemon" },
  { answer: "Hello Kitty", aliases: ["hello kitty cat"], category: "Cartoon", tier: 3, wiki: "Hello Kitty" },

  // Anime
  { answer: "Goku", aliases: ["son goku"], category: "Anime", tier: 2, wiki: "Goku" },
  { answer: "Naruto", aliases: ["naruto uzumaki"], category: "Anime", tier: 2, wiki: "Naruto" },
  { answer: "Sailor Moon", aliases: ["usagi tsukino"], category: "Anime", tier: 2, wiki: "Sailor Moon" },
  { answer: "Totoro", aliases: ["my neighbor totoro"], category: "Anime", tier: 2, wiki: "My Neighbor Totoro" },
  { answer: "Pikachu", aliases: ["pikachu pokemon", "pika"], category: "Anime", tier: 2, wiki: "Pikachu" },
  { answer: "Luffy", aliases: ["monkey d luffy"], category: "Anime", tier: 2, wiki: "Monkey D. Luffy" },
  { answer: "Eren Yeager", aliases: ["eren jaeger", "eren"], category: "Anime", tier: 3, wiki: "Eren Yeager" },
  { answer: "Light Yagami", aliases: ["kira"], category: "Anime", tier: 3, wiki: "Light Yagami" },
  { answer: "Gundam", aliases: ["mobile suit gundam"], category: "Anime", tier: 3, wiki: "Gundam" },
  { answer: "Astro Boy", aliases: ["atom", "tetsuwan atom"], category: "Anime", tier: 3, wiki: "Astro Boy" },

  // Comics
  { answer: "Superman", aliases: ["clark kent"], category: "Comics", tier: 2, wiki: "Superman" },
  { answer: "Spider-Man", aliases: ["spiderman", "peter parker"], category: "Comics", tier: 2, wiki: "Spider-Man" },
  { answer: "Batman", aliases: ["bruce wayne"], category: "Comics", tier: 2, wiki: "Batman" },
  { answer: "Wonder Woman", aliases: ["diana prince"], category: "Comics", tier: 2, wiki: "Wonder Woman" },
  { answer: "Iron Man", aliases: ["tony stark"], category: "Comics", tier: 2, wiki: "Iron Man" },
  { answer: "Asterix", aliases: ["asterix and obelix"], category: "Comics", tier: 3, wiki: "Asterix" },
  { answer: "Tintin", aliases: ["the adventures of tintin"], category: "Comics", tier: 3, wiki: "The Adventures of Tintin" },
  { answer: "One Piece", aliases: ["one piece anime", "one piece manga", "op"], category: "Comics", tier: 3, wiki: "One Piece" },

  // Company / Brand
  { answer: "Apple Logo", aliases: ["apple", "apple inc"], category: "Brand", tier: 2, wiki: "Apple Inc." },
  { answer: "Nike Swoosh", aliases: ["nike", "nike logo"], category: "Brand", tier: 2, wiki: "Nike, Inc." },
  { answer: "McDonald's", aliases: ["mcdonalds", "golden arches"], category: "Brand", tier: 2, wiki: "McDonald's" },
  { answer: "Tesla", aliases: ["tesla motors", "tesla inc"], category: "Brand", tier: 2, wiki: "Tesla, Inc." },
  { answer: "Google", aliases: ["google logo"], category: "Brand", tier: 2, wiki: "Google" },
  { answer: "Ferrari", aliases: ["ferrari logo"], category: "Brand", tier: 3, wiki: "Ferrari" },
  { answer: "Lamborghini", aliases: ["lambo"], category: "Brand", tier: 3, wiki: "Lamborghini" },
  { answer: "Starbucks", aliases: ["starbucks logo"], category: "Brand", tier: 3, wiki: "Starbucks" },

  // Drink
  { answer: "Espresso", aliases: ["espresso coffee"], category: "Drink", tier: 2, wiki: "Espresso" },
  { answer: "Matcha", aliases: ["matcha tea"], category: "Drink", tier: 2, wiki: "Matcha" },
  { answer: "Bubble Tea", aliases: ["boba tea", "boba"], category: "Drink", tier: 2, wiki: "Bubble tea" },
  { answer: "Mojito", aliases: ["mojitos", "mojito cocktail"], category: "Drink", tier: 2, wiki: "Mojito" },
  { answer: "Champagne", aliases: ["champagne wine", "champagnes"], category: "Drink", tier: 3, wiki: "Champagne" },
  { answer: "Sake", aliases: ["japanese sake"], category: "Drink", tier: 3, wiki: "Sake" },
  { answer: "Chai", aliases: ["masala chai"], category: "Drink", tier: 3, wiki: "Masala chai" },
  { answer: "Cappuccino", aliases: ["cappuccinos", "cappuccino coffee"], category: "Drink", tier: 3, wiki: "Cappuccino" },

  // Dessert
  { answer: "Macaron", aliases: ["macarons"], category: "Dessert", tier: 2, wiki: "Macaron" },
  { answer: "Tiramisu", aliases: ["tiramisu cake", "tiramisu dessert"], category: "Dessert", tier: 2, wiki: "Tiramisu" },
  { answer: "Cheesecake", aliases: ["cheese cake", "cheesecakes"], category: "Dessert", tier: 2, wiki: "Cheesecake" },
  { answer: "Mochi", aliases: ["mochis", "mochi rice cake", "daifuku"], category: "Dessert", tier: 2, wiki: "Mochi" },
  { answer: "Baklava", aliases: ["baclava", "baklava dessert", "baklawa"], category: "Dessert", tier: 3, wiki: "Baklava" },
  { answer: "Churro", aliases: ["churros"], category: "Dessert", tier: 3, wiki: "Churro" },
  { answer: "Pavlova", aliases: ["pavlova dessert", "pavlova cake"], category: "Dessert", tier: 3, wiki: "Pavlova" },
  { answer: "Gulab Jamun", aliases: ["gulab jamuns"], category: "Dessert", tier: 3, wiki: "Gulab jamun" },

  // Internet Culture
  { answer: "Gangnam Style", aliases: ["gangnam style psy"], category: "Internet", tier: 2, wiki: "Gangnam Style" },
  { answer: "Harlem Shake", aliases: ["harlem shake meme"], category: "Internet", tier: 2, wiki: "Harlem Shake (meme)" },
  { answer: "Grumpy Cat", aliases: ["grumpy cat meme"], category: "Internet", tier: 2, wiki: "Grumpy Cat" },
  { answer: "Doge", aliases: ["doge meme", "shiba inu meme"], category: "Internet", tier: 2, wiki: "Doge (meme)" },
  { answer: "Rickroll", aliases: ["rick roll", "never gonna give you up"], category: "Internet", tier: 3, wiki: "Rickrolling" },
  { answer: "Nyan Cat", aliases: ["nyan cat meme"], category: "Internet", tier: 3, wiki: "Nyan Cat" },
  { answer: "Distracted Boyfriend", aliases: ["distracted boyfriend meme"], category: "Internet", tier: 3, wiki: "Distracted boyfriend" },
  { answer: "Pepe the Frog", aliases: ["pepe meme"], category: "Internet", tier: 3, wiki: "Pepe the Frog" },

  // Religion
  { answer: "Vatican City", aliases: ["the vatican"], category: "Religion", tier: 2, wiki: "Vatican City" },
  { answer: "Mecca", aliases: ["makkah"], category: "Religion", tier: 2, wiki: "Mecca" },
  { answer: "Golden Temple", aliases: ["harmandir sahib"], category: "Religion", tier: 2, wiki: "Golden Temple" },
  { answer: "Bodh Gaya", aliases: ["bodhgaya"], category: "Religion", tier: 3, wiki: "Bodh Gaya" },
  { answer: "Torah", aliases: ["the torah"], category: "Religion", tier: 3, wiki: "Torah" },
  { answer: "Quran", aliases: ["koran", "the quran"], category: "Religion", tier: 3, wiki: "Quran" },
  { answer: "Bhagavad Gita", aliases: ["gita"], category: "Religion", tier: 3, wiki: "Bhagavad Gita" },
  { answer: "Dalai Lama", aliases: ["the dalai lama"], category: "Religion", tier: 3, wiki: "Dalai Lama" },

  // Philosophy
  { answer: "Plato's Cave", aliases: ["allegory of the cave", "plato cave"], category: "Philosophy", tier: 2, wiki: "Allegory of the cave" },
  { answer: "Nietzsche", aliases: ["friedrich nietzsche"], category: "Philosophy", tier: 2, wiki: "Friedrich Nietzsche" },
  { answer: "Socrates", aliases: ["sokrates", "socrates philosopher"], category: "Philosophy", tier: 2, wiki: "Socrates" },
  { answer: "Existentialism", aliases: ["existential philosophy", "existential"], category: "Philosophy", tier: 3, wiki: "Existentialism" },
  { answer: "Stoicism", aliases: ["stoic"], category: "Philosophy", tier: 3, wiki: "Stoicism" },
  { answer: "Yin and Yang", aliases: ["yin yang", "taijitu"], category: "Philosophy", tier: 3, wiki: "Yin and yang" },

  // Currency & Language
  { answer: "Yen", aliases: ["japanese yen"], category: "Currency", tier: 2, wiki: "Japanese yen" },
  { answer: "Euro", aliases: ["euro currency"], category: "Currency", tier: 2, wiki: "Euro" },
  { answer: "Bitcoin", aliases: ["btc"], category: "Currency", tier: 2, wiki: "Bitcoin" },
  { answer: "Dollar", aliases: ["us dollar", "american dollar"], category: "Currency", tier: 3, wiki: "United States dollar" },
  { answer: "Hieroglyphs", aliases: ["egyptian hieroglyphs"], category: "Language", tier: 2, wiki: "Egyptian hieroglyphs" },
  { answer: "Braille", aliases: ["braille alphabet", "braille system"], category: "Language", tier: 2, wiki: "Braille" },
  { answer: "Esperanto", aliases: ["esperanto language"], category: "Language", tier: 3, wiki: "Esperanto" },
  { answer: "Morse Code", aliases: ["morse", "morse code alphabet"], category: "Language", tier: 3, wiki: "Morse code" },

  // Tech - modern
  { answer: "iPhone", aliases: ["apple iphone"], category: "Tech", tier: 2, wiki: "IPhone" },
  { answer: "Tesla Model S", aliases: ["model s"], category: "Tech", tier: 2, wiki: "Tesla Model S" },
  { answer: "Oculus Rift", aliases: ["oculus", "meta quest"], category: "Tech", tier: 2, wiki: "Oculus Rift" },
  { answer: "ChatGPT", aliases: ["chat gpt"], category: "Tech", tier: 2, wiki: "ChatGPT" },
  { answer: "YouTube", aliases: ["youtube logo"], category: "Tech", tier: 2, wiki: "YouTube" },
  { answer: "Wikipedia", aliases: ["wikipedia logo"], category: "Tech", tier: 2, wiki: "Wikipedia" },
  { answer: "Linux", aliases: ["linux penguin", "tux"], category: "Tech", tier: 3, wiki: "Linux" },
  { answer: "Arduino", aliases: ["arduino board", "arduino uno"], category: "Tech", tier: 3, wiki: "Arduino" },
  { answer: "Raspberry Pi", aliases: ["raspberry pi computer"], category: "Tech", tier: 3, wiki: "Raspberry Pi" },
  { answer: "Smartwatch", aliases: ["apple watch"], category: "Tech", tier: 3, wiki: "Smartwatch" },

  // Vehicles expanded
  { answer: "Boeing 747", aliases: ["747", "jumbo jet"], category: "Vehicle", tier: 2, wiki: "Boeing 747" },
  { answer: "Orient Express", aliases: ["the orient express"], category: "Vehicle", tier: 2, wiki: "Orient Express" },
  { answer: "Harley-Davidson", aliases: ["harley davidson", "harley"], category: "Vehicle", tier: 2, wiki: "Harley-Davidson" },
  { answer: "Sputnik", aliases: ["sputnik 1"], category: "Vehicle", tier: 3, wiki: "Sputnik 1" },
  { answer: "Airbus A380", aliases: ["a380", "airbus"], category: "Vehicle", tier: 3, wiki: "Airbus A380" },

  // Nature / Expanded Geography
  { answer: "Mariana Trench", aliases: ["mariana trench deepest"], category: "Nature", tier: 2, wiki: "Mariana Trench" },
  { answer: "Sahara Desert", aliases: ["sahara"], category: "Nature", tier: 2, wiki: "Sahara" },
  { answer: "Amazon Rainforest", aliases: ["the amazon"], category: "Nature", tier: 2, wiki: "Amazon rainforest" },
  { answer: "Great Barrier Reef", aliases: ["great barrier", "great barrier reef australia"], category: "Nature", tier: 2, wiki: "Great Barrier Reef" },
  { answer: "Victoria Falls", aliases: ["victoria fall", "moci-oa-tunya", "mosi-oa-tunya"], category: "Nature", tier: 2, wiki: "Victoria Falls" },

  // === EXPANSION PACK 2 — More Math, Movie Quotes & Language Guess ===
  // Math — extra 40 (tier 1 easy, tier 2 medium, tier 3 hard)
  { type: "text", mode: "math", answer: "64", category: "Math", tier: 1, text: "8 × 8 = ?" },
  { type: "text", mode: "math", answer: "72", category: "Math", tier: 1, text: "9 × 8 = ?" },
  { type: "text", mode: "math", answer: "45", category: "Math", tier: 1, text: "9 × 5 = ?" },
  { type: "text", mode: "math", answer: "24", category: "Math", tier: 1, text: "6 × 4 = ?" },
  { type: "text", mode: "math", answer: "50", category: "Math", tier: 1, text: "100 ÷ 2 = ?" },
  { type: "text", mode: "math", answer: "12", category: "Math", tier: 1, text: "3 × 4 = ?" },
  { type: "text", mode: "math", answer: "18", category: "Math", tier: 1, text: "9 × 2 = ?" },
  { type: "text", mode: "math", answer: "27", category: "Math", tier: 1, text: "3³ = ?" },
  { type: "text", mode: "math", answer: "15", category: "Math", tier: 1, text: "30 ÷ 2 = ?" },
  { type: "text", mode: "math", answer: "11", category: "Math", tier: 1, text: "7 + 4 = ?" },
  { type: "text", mode: "math", answer: "144", category: "Math", tier: 2, text: "12² = ?" },
  { type: "text", mode: "math", answer: "125", category: "Math", tier: 2, text: "5³ = ?" },
  { type: "text", mode: "math", answer: "49", category: "Math", tier: 2, text: "7² = ?" },
  { type: "text", mode: "math", answer: "32", category: "Math", tier: 2, text: "2⁵ = ?" },
  { type: "text", mode: "math", answer: "21", category: "Math", tier: 2, text: "3 × 7 = ?" },
  { type: "text", mode: "math", answer: "18", category: "Math", tier: 2, text: "√324 = ?" },
  { type: "text", mode: "math", answer: "8", category: "Math", tier: 2, text: "√64 = ?" },
  { type: "text", mode: "math", answer: "11", category: "Math", tier: 2, text: "Prime after 7 = ?" },
  { type: "text", mode: "math", answer: "60", category: "Math", tier: 2, text: "LCM of 12 and 15 = ?" },
  { type: "text", mode: "math", answer: "6", category: "Math", tier: 2, text: "GCD of 18 and 24 = ?" },
  { type: "text", mode: "math", answer: "120", category: "Math", tier: 3, text: "5! = ?" },
  { type: "text", mode: "math", answer: "256", category: "Math", tier: 3, text: "16² = ?" },
  { type: "text", mode: "math", answer: "343", category: "Math", tier: 3, text: "7³ = ?" },
  { type: "text", mode: "math", answer: "512", category: "Math", tier: 3, text: "8³ = ?" },
  { type: "text", mode: "math", answer: "720", category: "Math", tier: 3, text: "6! = ?" },
  { type: "text", mode: "math", answer: "13", category: "Math", tier: 3, text: "√169 = ?" },
  { type: "text", mode: "math", answer: "19", category: "Math", tier: 3, text: "8th prime = ?" },
  { type: "text", mode: "math", answer: "144", category: "Math", tier: 3, text: "12 × 12 = ?" },
  { type: "text", mode: "math", answer: "1000", category: "Math", tier: 3, text: "10³ = ?" },
  { type: "text", mode: "math", answer: "84", category: "Math", tier: 3, text: "7 × 12 = ?" },
  { type: "text", mode: "math", answer: "96", category: "Math", tier: 1, text: "12 × 8 = ?" },
  { type: "text", mode: "math", answer: "54", category: "Math", tier: 1, text: "9 × 6 = ?" },
  { type: "text", mode: "math", answer: "81", category: "Math", tier: 1, text: "9² = ?" },
  { type: "text", mode: "math", answer: "121", category: "Math", tier: 2, text: "11² = ?" },
  { type: "text", mode: "math", answer: "169", category: "Math", tier: 2, text: "13² = ?" },
  { type: "text", mode: "math", answer: "196", category: "Math", tier: 2, text: "14² = ?" },
  { type: "text", mode: "math", answer: "225", category: "Math", tier: 3, text: "15² = ?" },
  { type: "text", mode: "math", answer: "361", category: "Math", tier: 3, text: "19² = ?" },
  { type: "text", mode: "math", answer: "2048", category: "Math", tier: 3, text: "2¹¹ = ?" },
  { type: "text", mode: "math", answer: "55", category: "Math", tier: 3, text: "Sum 1 to 10 = ?" },

  // Movie Quotes — extra 45 (category Quote, tiered)
  { type: "text", answer: "my father", category: "Quote", tier: 1, text: "Luke, I am your ______", desc: "Star Wars — Darth Vader" },
  { type: "text", answer: "king", category: "Quote", tier: 1, text: "I'm the ______ of the world!", desc: "Titanic" },
  { type: "text", answer: "offer", category: "Quote", tier: 1, text: "I'm gonna make him an ______ he can't refuse", desc: "The Godfather" },
  { type: "text", answer: "love", category: "Quote", tier: 1, text: "I'm just a girl, standing in front of a boy, asking him to ______ her", desc: "Notting Hill — Julia Roberts" },
  { type: "text", answer: "precious", category: "Quote", tier: 1, text: "My ______", desc: "The Lord of the Rings — Gollum" },
  { type: "text", answer: "tomorrow", category: "Quote", tier: 1, text: "Frankly, my dear, I don't give a damn — Gone with the ______", desc: "Gone with the Wind (misattributed line)" },
  { type: "text", answer: "friend", category: "Quote", tier: 1, text: "You've got a ______ in me", desc: "Toy Story" },
  { type: "text", answer: "alive", category: "Quote", tier: 1, text: "It's ______! It's alive!", desc: "Frankenstein (1931)" },
  { type: "text", answer: "house", category: "Quote", tier: 1, text: "There's no place like ______", desc: "The Wizard of Oz" },
  { type: "text", answer: "stella", category: "Quote", tier: 1, text: "Stella! Hey, ______!", desc: "A Streetcar Named Desire" },
  { type: "text", answer: "money", category: "Quote", tier: 1, text: "Show me the ______!", desc: "Jerry Maguire" },
  { type: "text", answer: "can't handle", category: "Quote", tier: 1, text: "You ______ the truth!", desc: "A Few Good Men" },
  { type: "text", answer: "life", category: "Quote", tier: 1, text: "Life is like a box of chocolates — you never know what you're gonna get (missing word: ______)", desc: "Forrest Gump" },
  { type: "text", answer: "bond", category: "Quote", tier: 1, text: "The name's Bond, James ______", desc: "James Bond" },
  { type: "text", answer: "truth", category: "Quote", tier: 1, text: "You want the ______? You can't handle the truth!", desc: "A Few Good Men" },
  { type: "text", answer: "hello", category: "Quote", tier: 1, text: "You had me at ______", desc: "Jerry Maguire" },
  { type: "text", answer: "lion", category: "Quote", tier: 1, text: "Hakuna Matata — it means no worries (animal in phrase: ______)", desc: "The Lion King" },
  { type: "text", answer: "mirror", category: "Quote", tier: 1, text: "Mirror, ______ on the wall", desc: "Snow White" },
  { type: "text", answer: "infinite", category: "Quote", tier: 2, text: "To ______ and beyond!", desc: "Toy Story — Buzz Lightyear (variation)" },
  { type: "text", answer: "rosebud", category: "Quote", tier: 2, text: "______", desc: "Citizen Kane — last word" },
  { type: "text", answer: "shining", category: "Quote", tier: 2, text: "Here's Johnny!", desc: "The Shining" },
  { type: "text", answer: "mordor", category: "Quote", tier: 2, text: "One does not simply walk into ______", desc: "Lord of the Rings — Boromir" },
  { type: "text", answer: "faith", category: "Quote", tier: 2, text: "I find your lack of ______ disturbing", desc: "Star Wars — Darth Vader" },
  { type: "text", answer: "father", category: "Quote", tier: 2, text: "No, I am your ______", desc: "Star Wars — Darth Vader" },
  { type: "text", answer: "phone", category: "Quote", tier: 2, text: "E.T. ______ home", desc: "E.T." },
  { type: "text", answer: "great", category: "Quote", tier: 2, text: "I'm king of the world! — Titanic (missing word: ______)", desc: "Titanic — famously 'king'" },
  { type: "text", answer: "forget", category: "Quote", tier: 2, text: "Never gonna give you up, never gonna let you ______", desc: "Rick Astley — also meme" },
  { type: "text", answer: "danger", category: "Quote", tier: 2, text: "I am the one who knocks — also: I am the ______", desc: "Breaking Bad — Walter White" },
  { type: "text", answer: "heisenberg", category: "Quote", tier: 2, text: "Say my name — ______", desc: "Breaking Bad — Walter White alias" },
  { type: "text", answer: "wingardium", category: "Quote", tier: 1, text: "______ Leviosa", desc: "Harry Potter" },
  { type: "text", answer: "avengers", category: "Quote", tier: 1, text: "______ assemble!", desc: "Marvel — Avengers" },
  { type: "text", answer: "wax", category: "Quote", tier: 2, text: "Wax on, ______ off", desc: "The Karate Kid" },
  { type: "text", answer: "potter", category: "Quote", tier: 1, text: "You're a wizard, Harry — surname: ______", desc: "Harry Potter" },
  { type: "text", answer: "titanic", category: "Quote", tier: 2, text: "I'm the king of the world! — ship: ______", desc: "Titanic" },
  { type: "text", answer: "yoda", category: "Quote", tier: 2, text: "Do or do not, there is no try — said by ______", desc: "Star Wars — Yoda" },
  { type: "text", answer: "gump", category: "Quote", tier: 2, text: "Run, Forrest, run! — surname: ______", desc: "Forrest Gump" },
  { type: "text", answer: "simba", category: "Quote", tier: 2, text: "Remember who you are — said to ______", desc: "The Lion King — Simba" },
  { type: "text", answer: "dory", category: "Quote", tier: 1, text: "Just keep swimming — said by ______", desc: "Finding Nemo — Dory" },
  { type: "text", answer: "buzz", category: "Quote", tier: 1, text: "To infinity and beyond — said by ______ Lightyear", desc: "Toy Story — Buzz" },
  { type: "text", answer: "leia", category: "Quote", tier: 2, text: "Help me, Obi-Wan Kenobi. You're my only hope — Princess ______", desc: "Star Wars — Leia" },

  // Language Guess — new topic (guess the language or translation)
  // Mode quiz with category Language — text is phrase/question, answer is language/word
  { type: "text", mode: "quiz", answer: "French", aliases: ["francais", "français"], category: "Language", tier: 1, text: "What language is this? 'Bonjour, comment ça va?'" },
  { type: "text", mode: "quiz", answer: "Spanish", aliases: ["espanol", "español"], category: "Language", tier: 1, text: "What language is this? 'Hola, ¿cómo estás?'" },
  { type: "text", mode: "quiz", answer: "German", aliases: ["deutsch"], category: "Language", tier: 1, text: "What language is this? 'Guten Tag, wie geht es dir?'" },
  { type: "text", mode: "quiz", answer: "Italian", aliases: ["italiano"], category: "Language", tier: 1, text: "What language is this? 'Ciao, come stai?'" },
  { type: "text", mode: "quiz", answer: "Japanese", aliases: ["nihongo"], category: "Language", tier: 1, text: "What language is this? 'Konnichiwa, genki desu ka?'" },
  { type: "text", mode: "quiz", answer: "Korean", aliases: ["hangul", "hanguk"], category: "Language", tier: 1, text: "What language is this? 'Annyeonghaseyo?'" },
  { type: "text", mode: "quiz", answer: "Portuguese", aliases: ["portugues", "português"], category: "Language", tier: 1, text: "What language is this? 'Olá, como vai?'" },
  { type: "text", mode: "quiz", answer: "Russian", aliases: ["russkiy"], category: "Language", tier: 1, text: "What language is this? 'Privet, kak dela?'" },
  { type: "text", mode: "quiz", answer: "Arabic", aliases: ["al arabiya"], category: "Language", tier: 1, text: "What language is this? 'Marhaba, kayf halak?'" },
  { type: "text", mode: "quiz", answer: "Hindi", aliases: ["hindustani"], category: "Language", tier: 1, text: "What language is this? 'Namaste, kaise ho?'" },
  { type: "text", mode: "quiz", answer: "hello", category: "Language", tier: 1, text: "Translate to English: 'Hola' (Spanish)" },
  { type: "text", mode: "quiz", answer: "goodbye", aliases: ["bye"], category: "Language", tier: 1, text: "Translate to English: 'Au revoir' (French)" },
  { type: "text", mode: "quiz", answer: "thank you", aliases: ["thanks"], category: "Language", tier: 1, text: "Translate to English: 'Arigatou' (Japanese)" },
  { type: "text", mode: "quiz", answer: "yes", category: "Language", tier: 1, text: "Translate to English: 'Ja' (German)" },
  { type: "text", mode: "quiz", answer: "no", category: "Language", tier: 1, text: "Translate to English: 'Non' (French)" },
  { type: "text", mode: "quiz", answer: "water", category: "Language", tier: 2, text: "Translate to English: 'Agua' (Spanish)" },
  { type: "text", mode: "quiz", answer: "love", category: "Language", tier: 2, text: "Translate to English: 'Amour' (French)" },
  { type: "text", mode: "quiz", answer: "friend", category: "Language", tier: 2, text: "Translate to English: 'Amigo' (Spanish)" },
  { type: "text", mode: "quiz", answer: "cat", category: "Language", tier: 2, text: "Translate to English: 'Neko' (Japanese)" },
  { type: "text", mode: "quiz", answer: "dog", category: "Language", tier: 2, text: "Translate to English: 'Hund' (German)" },
  { type: "text", mode: "quiz", answer: "mandarin", aliases: ["chinese"], category: "Language", tier: 2, text: "What language is this? 'Ni hao, ni hao ma?'" },
  { type: "text", mode: "quiz", answer: "dutch", aliases: ["nederlands"], category: "Language", tier: 2, text: "What language is this? 'Goedemorgen, hoe gaat het?'" },
  { type: "text", mode: "quiz", answer: "swedish", aliases: ["svenska"], category: "Language", tier: 2, text: "What language is this? 'Hej, hur mår du?'" },
  { type: "text", mode: "quiz", answer: "greek", aliases: ["ellinika"], category: "Language", tier: 2, text: "What language is this? 'Geia sou, ti kaneis?'" },
  { type: "text", mode: "quiz", answer: "turkish", aliases: ["turkce"], category: "Language", tier: 3, text: "What language is this? 'Merhaba, nasılsın?'" },
  { type: "text", mode: "quiz", answer: "polish", aliases: ["polski"], category: "Language", tier: 3, text: "What language is this? 'Cześć, jak się masz?'" },
  { type: "text", mode: "quiz", answer: "thai", category: "Language", tier: 3, text: "What language is this? 'Sawasdee khrap?'" },
  { type: "text", mode: "quiz", answer: "hebrew", aliases: ["ivrit"], category: "Language", tier: 3, text: "What language is this? 'Shalom, ma shlomkha?'" },
  { type: "text", mode: "quiz", answer: "swahili", category: "Language", tier: 3, text: "What language is this? 'Jambo, habari gani?'" },
  { type: "text", mode: "quiz", answer: "finnish", aliases: ["suomi"], category: "Language", tier: 3, text: "What language is this? 'Moi, mitä kuuluu?'" },
  { type: "text", mode: "quiz", answer: "book", category: "Language", tier: 2, text: "Translate to English: 'Buch' (German)" },
  { type: "text", mode: "quiz", answer: "house", category: "Language", tier: 2, text: "Translate to English: 'Casa' (Spanish/Italian)" },
  { type: "text", mode: "quiz", answer: "moon", category: "Language", tier: 2, text: "Translate to English: 'Luna' (Spanish/Italian)" },
  { type: "text", mode: "quiz", answer: "sun", category: "Language", tier: 3, text: "Translate to English: 'Soleil' (French)" },
  { type: "text", mode: "quiz", answer: "night", category: "Language", tier: 3, text: "Translate to English: 'Noche' (Spanish)" },

  // Extra Topics — quick fill: Mythology, Space, History, Geography image items
  { answer: "Zeus Statue", aliases: ["statue of zeus"], category: "Mythology", tier: 2, wiki: "Statue of Zeus at Olympia" },
  { answer: "Valhalla", aliases: ["valhalla hall", "walhalla"], category: "Mythology", tier: 3, wiki: "Valhalla" },
  { answer: "Excalibur", aliases: ["king arthur sword"], category: "Mythology", tier: 3, wiki: "Excalibur" },
  { answer: "Neptune", aliases: ["planet neptune"], category: "Space", tier: 2, wiki: "Neptune" },
  { answer: "Andromeda Galaxy", aliases: ["andromeda"], category: "Space", tier: 3, wiki: "Andromeda Galaxy" },
  { answer: "Eiffel Tower", aliases: ["la tour eiffel", "iron lady", "tour eiffel"], category: "Landmark", tier: 1, wiki: "Eiffel Tower" },
  { answer: "Sushi", aliases: ["sushi roll", "sushis", "nigiri"], category: "Food", tier: 2, wiki: "Sushi" },
  { answer: "Kimchi", aliases: ["kimchee", "kimuchi", "korean kimchi"], category: "Food", tier: 3, wiki: "Kimchi" },
  { answer: "Origami", aliases: ["origami crane"], category: "Art", tier: 2, wiki: "Origami" },
  { answer: "Calligraphy", aliases: ["chinese calligraphy"], category: "Art", tier: 3, wiki: "Calligraphy" }
];
