"use strict";

const CURATED_ITEMS = [
  { answer: "Eiffel Tower", aliases: ["la tour eiffel", "tour eiffel"], category: "Landmark", tier: 1 },
  { answer: "Mona Lisa", aliases: ["la gioconda", "la joconde"], category: "Artwork", tier: 1 },
  { answer: "Pikachu", aliases: [], category: "Game Character", tier: 1 },
  { answer: "Mario", aliases: ["super mario"], category: "Game Character", tier: 1 },
  { answer: "Coca-Cola", aliases: ["coke", "coca cola"], category: "Brand", tier: 1 },
  { answer: "Big Ben", aliases: [], category: "Landmark", tier: 1 },
  { answer: "Statue of Liberty", aliases: ["liberty statue"], category: "Landmark", tier: 1 },
  { answer: "Golden Retriever", aliases: ["golden retriever dog"], category: "Animal", tier: 1 },
  { answer: "Pizza", aliases: ["pizzas"], category: "Food", tier: 1 },
  { answer: "iPhone", aliases: ["apple iphone", "i phone"], category: "Object", tier: 1, wiki: "IPhone" },
  { answer: "The Beatles", aliases: ["beatles"], category: "Band", tier: 1 },
  { answer: "Albert Einstein", aliases: ["einstein"], category: "Scientist", tier: 1 },
  { answer: "Batman", aliases: ["the batman"], category: "Movie Character", tier: 1 },
  { answer: "Darth Vader", aliases: ["vader", "lord vader"], category: "Movie Character", tier: 1 },
  { answer: "Harry Potter", aliases: ["harry potter series"], category: "Movie", tier: 1 },
  { answer: "William Shakespeare", aliases: ["shakespeare"], category: "Author", tier: 1 },
  { answer: "Lion", aliases: ["lions"], category: "Animal", tier: 1 },
  { answer: "Giraffe", aliases: ["giraffes"], category: "Animal", tier: 1 },
  { answer: "The Moon", aliases: ["moon", "luna"], category: "Space", tier: 1, wiki: "Moon" },
  { answer: "The Sun", aliases: ["sun", "sol"], category: "Space", tier: 1, wiki: "Sun" },
  { answer: "Mars", aliases: ["planet mars", "the red planet"], category: "Space", tier: 1 },
  { answer: "Tyrannosaurus rex", aliases: ["t rex", "trex", "tyrannosaurus", "t-rex"], category: "Dinosaur", tier: 1, wiki: "Tyrannosaurus" },
  { answer: "Ice cream", aliases: ["icecream"], category: "Food", tier: 1 },
  { answer: "Hamburger", aliases: ["burger", "burgers"], category: "Food", tier: 1 },
  { answer: "Hot dog", aliases: ["hotdog"], category: "Food", tier: 1 },
  { answer: "Guitar", aliases: ["acoustic guitar"], category: "Object", tier: 1 },
  { answer: "Piano", aliases: ["grand piano"], category: "Music", tier: 1 },
  { answer: "Michael Jackson", aliases: ["mj", "jacko"], category: "Person", tier: 1 },
  { answer: "Taj Mahal", aliases: ["the taj mahal"], category: "Landmark", tier: 1 },
  { answer: "Mount Everest", aliases: ["everest", "sagarmatha"], category: "Landmark", tier: 1 },
  { answer: "Great Wall of China", aliases: ["the great wall", "great wall"], category: "Landmark", tier: 1 },
  { answer: "Titanic", aliases: ["rms titanic", "titanic 1997"], category: "Movie", tier: 1, wiki: "Titanic (1997 film)" },

  { answer: "Christ the Redeemer", aliases: ["cristo redentor", "christ the redeemer statue"], category: "Landmark", tier: 2, wiki: "Christ the Redeemer (statue)" },
  { answer: "Leaning Tower of Pisa", aliases: ["tower of pisa", "pisa tower"], category: "Landmark", tier: 2 },
  { answer: "Colosseum", aliases: ["coliseum", "flavian amphitheatre"], category: "Landmark", tier: 2 },
  { answer: "Sydney Opera House", aliases: [], category: "Landmark", tier: 2 },
  { answer: "Sagrada Família", aliases: ["sagrada familia"], category: "Landmark", tier: 2 },
  { answer: "Mount Fuji", aliases: ["fuji", "fujisan"], category: "Landmark", tier: 2 },
  { answer: "Niagara Falls", aliases: ["niagara"], category: "Landmark", tier: 2 },
  { answer: "Grand Canyon", aliases: ["the grand canyon"], category: "Landmark", tier: 2 },
  { answer: "Great Barrier Reef", aliases: [], category: "Nature", tier: 2 },
  { answer: "Amazon Rainforest", aliases: ["the amazon", "amazon jungle", "the amazon rainforest"], category: "Nature", tier: 2 },
  { answer: "Sahara", aliases: ["sahara desert", "the sahara"], category: "Nature", tier: 2 },
  { answer: "Uluru", aliases: ["ayers rock", "ayer's rock", "uluru rock"], category: "Landmark", tier: 2 },
  { answer: "Victoria Falls", aliases: [], category: "Landmark", tier: 2 },
  { answer: "Moai", aliases: ["easter island head", "easter island statues", "moai statues"], category: "Landmark", tier: 2 },
  { answer: "Great Sphinx of Giza", aliases: ["sphinx", "the sphinx", "giza sphinx"], category: "Landmark", tier: 2 },
  { answer: "Terracotta Army", aliases: ["terracotta warriors", "terracotta soldiers"], category: "Landmark", tier: 2 },
  { answer: "Tutankhamun", aliases: ["king tut", "tut", "tutankhamen"], category: "History", tier: 2 },
  { answer: "Cleopatra", aliases: ["cleopatra vii"], category: "History", tier: 2 },
  { answer: "Julius Caesar", aliases: ["caesar"], category: "History", tier: 2 },
  { answer: "Napoleon", aliases: ["napoleon bonaparte"], category: "History", tier: 2 },
  { answer: "Leonardo da Vinci", aliases: ["da vinci", "leonardo"], category: "Person", tier: 2 },
  { answer: "Mahatma Gandhi", aliases: ["gandhi"], category: "Person", tier: 2 },
  { answer: "Abraham Lincoln", aliases: ["lincoln"], category: "Person", tier: 2 },
  { answer: "Anne Frank", aliases: [], category: "Person", tier: 2 },
  { answer: "Nelson Mandela", aliases: ["mandela"], category: "Person", tier: 2 },
  { answer: "Martin Luther King Jr.", aliases: ["mlk", "martin luther king"], category: "Person", tier: 2 },
  { answer: "Elizabeth II", aliases: ["queen elizabeth", "queen elizabeth ii"], category: "Person", tier: 2 },
  { answer: "Gold", aliases: ["gold element", "au"], category: "Chemistry", tier: 2 },
  { answer: "Mercury", aliases: ["mercury element", "quicksilver", "hg"], category: "Chemistry", tier: 2, wiki: "Mercury (element)" },
  { answer: "Helium", aliases: ["he"], category: "Chemistry", tier: 2 },
  { answer: "Sulfur", aliases: ["sulphur", "brimstone"], category: "Chemistry", tier: 2 },
  { answer: "Diamond", aliases: ["diamonds"], category: "Chemistry", tier: 2 },
  { answer: "Caffeine", aliases: [], category: "Chemistry", tier: 2 },
  { answer: "DNA", aliases: ["deoxyribonucleic acid", "dna helix"], category: "Biology", tier: 2 },
  { answer: "Human Brain", aliases: ["brain"], category: "Biology", tier: 2, wiki: "Human brain" },
  { answer: "Human Skeleton", aliases: ["skeleton", "bones"], category: "Biology", tier: 2, wiki: "Human skeleton" },
  { answer: "Human Eye", aliases: ["eye"], category: "Biology", tier: 2, wiki: "Human eye" },
  { answer: "Fingerprint", aliases: ["fingerprints", "finger print"], category: "Biology", tier: 2 },
  { answer: "Stethoscope", aliases: [], category: "Medicine", tier: 2 },
  { answer: "Syringe", aliases: ["hypodermic syringe", "needle"], category: "Medicine", tier: 2 },
  { answer: "X-ray", aliases: ["xray", "x ray", "radiograph"], category: "Medicine", tier: 2 },
  { answer: "Microscope", aliases: [], category: "Object", tier: 2 },
  { answer: "Telescope", aliases: ["refracting telescope"], category: "Object", tier: 2 },
  { answer: "Saturn", aliases: ["planet saturn"], category: "Space", tier: 2 },
  { answer: "Jupiter", aliases: ["planet jupiter"], category: "Space", tier: 2 },
  { answer: "Venus", aliases: ["venus planet", "morning star"], category: "Space", tier: 2, wiki: "Venus" },
  { answer: "Andromeda Galaxy", aliases: ["andromeda"], category: "Space", tier: 2 },
  { answer: "Milky Way", aliases: ["the milky way"], category: "Space", tier: 2 },
  { answer: "International Space Station", aliases: ["iss"], category: "Space", tier: 2 },
  { answer: "Apollo 11", aliases: ["apollo eleven", "apollo 11 mission"], category: "Space", tier: 2 },
  { answer: "Saturn V", aliases: ["saturn 5", "saturn five rocket", "saturn v rocket"], category: "Space", tier: 2 },
  { answer: "Hubble Space Telescope", aliases: ["hubble", "hubble telescope"], category: "Space", tier: 2 },
  { answer: "Wright Flyer", aliases: ["the wright flyer", "wright brothers plane", "first airplane", "first plane"], category: "History", tier: 2 },
  { answer: "Printing Press", aliases: ["the printing press"], category: "History", tier: 2, wiki: "Printing press" },
  { answer: "Phonograph", aliases: ["gramophone", "record player"], category: "Object", tier: 2 },
  { answer: "Vinyl Record", aliases: ["vinyl", "lp", "record"], category: "Object", tier: 2, wiki: "Phonograph record" },
  { answer: "Floppy Disk", aliases: ["diskette", "floppy"], category: "Object", tier: 2 },
  { answer: "Cassette Tape", aliases: ["cassette", "audio cassette"], category: "Object", tier: 2, wiki: "Cassette tape" },
  { answer: "Typewriter", aliases: [], category: "Object", tier: 2 },
  { answer: "Hourglass", aliases: ["sand timer", "sandglass", "sand clock"], category: "Object", tier: 2 },
  { answer: "Compass", aliases: ["magnetic compass"], category: "Object", tier: 2 },
  { answer: "Rubik's Cube", aliases: ["rubiks cube", "rubik cube", "magic cube"], category: "Object", tier: 2 },
  { answer: "Lego", aliases: ["legos", "lego bricks"], category: "Object", tier: 2 },
  { answer: "Giant Panda", aliases: ["panda", "pandas"], category: "Animal", tier: 2, wiki: "Giant panda" },
  { answer: "Polar Bear", aliases: [], category: "Animal", tier: 2 },
  { answer: "Koala", aliases: ["koala bear"], category: "Animal", tier: 2 },
  { answer: "Kangaroo", aliases: [], category: "Animal", tier: 2 },
  { answer: "Zebra", aliases: ["zebras"], category: "Animal", tier: 2 },
  { answer: "Emperor Penguin", aliases: ["penguin"], category: "Animal", tier: 2, wiki: "Emperor penguin" },
  { answer: "Flamingo", aliases: ["flamingos"], category: "Animal", tier: 2 },
  { answer: "Bald Eagle", aliases: ["eagle", "american eagle"], category: "Animal", tier: 2 },
  { answer: "Orca", aliases: ["killer whale", "orca whale"], category: "Animal", tier: 2, wiki: "Orca" },
  { answer: "Blue Whale", aliases: [], category: "Animal", tier: 2 },
  { answer: "Dolphin", aliases: ["dolphins"], category: "Animal", tier: 2 },
  { answer: "Great White Shark", aliases: ["great white", "white shark"], category: "Animal", tier: 2 },
  { answer: "Octopus", aliases: ["octopi", "octopuses"], category: "Animal", tier: 2 },
  { answer: "Jellyfish", aliases: ["jelly fish"], category: "Animal", tier: 2 },
  { answer: "Butterfly", aliases: ["monarch butterfly", "butterflies"], category: "Animal", tier: 2, wiki: "Monarch butterfly" },
  { answer: "Bee", aliases: ["honey bee", "honeybee", "bumblebee"], category: "Animal", tier: 2, wiki: "Western honey bee" },
  { answer: "Sunflower", aliases: ["sunflowers"], category: "Plant", tier: 2, wiki: "Common sunflower" },
  { answer: "Cactus", aliases: ["cacti", "cactuses"], category: "Plant", tier: 2 },
  { answer: "Venus Flytrap", aliases: ["flytrap", "venus fly trap"], category: "Plant", tier: 2 },
  { answer: "Bonsai", aliases: ["bonsai tree"], category: "Plant", tier: 2 },
  { answer: "Bamboo", aliases: ["bamboo plant"], category: "Plant", tier: 2 },
  { answer: "Croissant", aliases: ["croissants"], category: "Food", tier: 2 },
  { answer: "Taco", aliases: ["tacos"], category: "Food", tier: 2 },
  { answer: "Ramen", aliases: ["ramen noodles"], category: "Food", tier: 2 },
  { answer: "Sushi", aliases: [], category: "Food", tier: 2 },
  { answer: "Chocolate", aliases: [], category: "Food", tier: 2 },
  { answer: "Banana", aliases: ["bananas"], category: "Food", tier: 2 },
  { answer: "Pineapple", aliases: ["pineapples"], category: "Food", tier: 2 },
  { answer: "Avocado", aliases: ["avocados"], category: "Food", tier: 2 },
  { answer: "Watermelon", aliases: ["watermelons"], category: "Food", tier: 2 },
  { answer: "Pretzel", aliases: ["pretzels"], category: "Food", tier: 2 },
  { answer: "Doughnut", aliases: ["donut", "donuts", "doughnuts"], category: "Food", tier: 2 },
  { answer: "French Fries", aliases: ["fries", "chips"], category: "Food", tier: 2 },
  { answer: "Violin", aliases: ["fiddle"], category: "Music", tier: 2 },
  { answer: "Saxophone", aliases: ["sax"], category: "Music", tier: 2 },
  { answer: "Trumpet", aliases: ["trumpets"], category: "Music", tier: 2 },
  { answer: "Drum Kit", aliases: ["drums", "drum set"], category: "Music", tier: 2, wiki: "Drum kit" },
  { answer: "Harp", aliases: ["harps"], category: "Music", tier: 2 },
  { answer: "Accordion", aliases: ["squeezebox"], category: "Music", tier: 2 },
  { answer: "Mozart", aliases: ["wolfgang amadeus mozart", "amadeus"], category: "Composer", tier: 2, wiki: "Wolfgang Amadeus Mozart" },
  { answer: "Beethoven", aliases: ["ludwig van beethoven"], category: "Composer", tier: 2, wiki: "Ludwig van Beethoven" },
  { answer: "Bach", aliases: ["johann sebastian bach", "j s bach"], category: "Composer", tier: 2, wiki: "Johann Sebastian Bach" },
  { answer: "Sumo", aliases: ["sumo wrestling"], category: "Sport", tier: 2 },
  { answer: "Archery", aliases: ["archer", "bow and arrow"], category: "Sport", tier: 2 },
  { answer: "Bowling", aliases: ["ten pin bowling"], category: "Sport", tier: 2 },
  { answer: "Table Tennis", aliases: ["ping pong"], category: "Sport", tier: 2 },
  { answer: "Skateboarding", aliases: ["skateboard"], category: "Sport", tier: 2 },
  { answer: "Surfing", aliases: ["surfboard", "surf"], category: "Sport", tier: 2 },
  { answer: "Chess", aliases: ["chess board", "chessboard"], category: "Game", tier: 2 },
  { answer: "Jenga", aliases: [], category: "Game", tier: 2 },
  { answer: "Yo-yo", aliases: ["yoyo", "yo yo"], category: "Game", tier: 2 },
  { answer: "Light Bulb", aliases: ["lightbulb", "bulb", "the light bulb"], category: "Object", tier: 2, wiki: "Incandescent light bulb" },
  { answer: "Wind Turbine", aliases: ["wind turbines"], category: "Object", tier: 2 },
  { answer: "Ferris Wheel", aliases: ["ferriswheel"], category: "Object", tier: 2 },
  { answer: "Roller Coaster", aliases: ["rollercoaster"], category: "Object", tier: 2 },
  { answer: "Slot Machine", aliases: ["slot machines", "one armed bandit", "fruit machine"], category: "Object", tier: 2 },
  { answer: "Carousel", aliases: ["merry go round", "merry-go-round", "carrousel"], category: "Object", tier: 2 },
  { answer: "Pinball", aliases: ["pinball machine"], category: "Game", tier: 2 },
  { answer: "Magnet", aliases: ["magnets", "horseshoe magnet"], category: "Physics", tier: 2 },
  { answer: "Lightning", aliases: ["lightning bolt", "thunderbolt"], category: "Physics", tier: 2 },
  { answer: "Rainbow", aliases: ["rainbows"], category: "Physics", tier: 2 },
  { answer: "Newton's Cradle", aliases: ["newtons cradle", "newton cradle"], category: "Physics", tier: 2 },
  { answer: "Tesla Coil", aliases: ["tesla coils"], category: "Physics", tier: 2 },
  { answer: "Isaac Newton", aliases: ["newton", "sir isaac newton"], category: "Scientist", tier: 2 },
  { answer: "Marie Curie", aliases: ["curie", "madame curie"], category: "Scientist", tier: 2 },
  { answer: "Nikola Tesla", aliases: ["tesla"], category: "Scientist", tier: 2 },
  { answer: "Stephen Hawking", aliases: ["hawking"], category: "Scientist", tier: 2 },
  { answer: "Charles Darwin", aliases: ["darwin"], category: "Scientist", tier: 2 },
  { answer: "Galileo Galilei", aliases: ["galileo"], category: "Scientist", tier: 2 },
  { answer: "The Scream", aliases: ["scream"], category: "Artwork", tier: 2 },
  { answer: "The Starry Night", aliases: ["starry night", "starry night van gogh"], category: "Artwork", tier: 2 },
  { answer: "David", aliases: ["michelangelo david", "statue of david", "david statue"], category: "Artwork", tier: 2, wiki: "David (Michelangelo)" },
  { answer: "Venus de Milo", aliases: ["venus statue", "aphrodite of milos"], category: "Artwork", tier: 2 },
  { answer: "The Thinker", aliases: ["thinker", "rodin thinker", "le penseur"], category: "Artwork", tier: 2 },
  { answer: "Girl with a Pearl Earring", aliases: ["girl with pearl earring"], category: "Artwork", tier: 2 },
  { answer: "The Great Wave", aliases: ["great wave", "the great wave off kanagawa", "great wave off kanagawa"], category: "Artwork", tier: 2, wiki: "The Great Wave off Kanagawa" },
  { answer: "Parthenon", aliases: ["the parthenon"], category: "Landmark", tier: 2 },
  { answer: "Notre-Dame", aliases: ["notre dame", "notre dame cathedral", "notre dame de paris"], category: "Landmark", tier: 2, wiki: "Notre-Dame de Paris" },
  { answer: "Saint Basil's Cathedral", aliases: ["st basils cathedral", "st basil cathedral", "basils cathedral"], category: "Landmark", tier: 2 },
  { answer: "Hagia Sophia", aliases: [], category: "Landmark", tier: 2 },
  { answer: "Chichén Itzá", aliases: ["chichen itza", "el castillo"], category: "Landmark", tier: 2, wiki: "Chichen Itza" },
  { answer: "Petra", aliases: ["petra jordan"], category: "Landmark", tier: 2 },
  { answer: "Neuschwanstein Castle", aliases: ["neuschwanstein"], category: "Landmark", tier: 2 },
  { answer: "Elephant", aliases: ["african elephant", "african bush elephant"], category: "Animal", tier: 2, wiki: "African bush elephant" },
  { answer: "Hippopotamus", aliases: ["hippo", "hippos"], category: "Animal", tier: 2 },
  { answer: "Rhinoceros", aliases: ["rhino", "rhinos"], category: "Animal", tier: 2 },
  { answer: "Cheetah", aliases: ["cheetahs"], category: "Animal", tier: 2 },
  { answer: "Gorilla", aliases: ["gorillas"], category: "Animal", tier: 2 },
  { answer: "Camel", aliases: ["camels"], category: "Animal", tier: 2 },
  { answer: "Crocodile", aliases: ["crocs", "crocodiles"], category: "Animal", tier: 2 },
  { answer: "Tetris", aliases: [], category: "Game", tier: 2 },

  { answer: "Machu Picchu", aliases: ["machupicchu", "machu picchu ruins"], category: "Landmark", tier: 3 },
  { answer: "Stonehenge", aliases: ["stone henge"], category: "Landmark", tier: 3 },
  { answer: "Angkor Wat", aliases: [], category: "Landmark", tier: 3 },
  { answer: "Mont-Saint-Michel", aliases: ["mont saint michel", "mont st michel", "le mont saint michel"], category: "Landmark", tier: 3 },
  { answer: "Aqueduct of Segovia", aliases: ["segovia aqueduct", "the aqueduct of segovia"], category: "Landmark", tier: 3 },
  { answer: "Salar de Uyuni", aliases: ["uyuni", "salt flats", "uyuni salt flats"], category: "Nature", tier: 3 },
  { answer: "Great Blue Hole", aliases: ["the great blue hole", "blue hole belize"], category: "Nature", tier: 3 },
  { answer: "Galápagos Islands", aliases: ["galapagos", "the galapagos"], category: "Nature", tier: 3 },
  { answer: "Yellowstone National Park", aliases: ["yellowstone"], category: "Nature", tier: 3 },
  { answer: "Old Faithful", aliases: ["old faithful geyser"], category: "Nature", tier: 3 },
  { answer: "Aurora", aliases: ["northern lights", "aurora borealis", "southern lights", "aurora australis"], category: "Nature", tier: 3 },
  { answer: "Tornado", aliases: ["tornadoes", "twister"], category: "Nature", tier: 3 },
  { answer: "Waterspout", aliases: ["water spout"], category: "Nature", tier: 3 },
  { answer: "Iceberg", aliases: ["icebergs"], category: "Nature", tier: 3 },
  { answer: "Glacier", aliases: ["glaciers"], category: "Nature", tier: 3 },
  { answer: "Geyser", aliases: ["geysers"], category: "Nature", tier: 3 },
  { answer: "Meteor Crater", aliases: ["barringer crater"], category: "Nature", tier: 3 },
  { answer: "Ammonite", aliases: ["ammonites"], category: "Fossil", tier: 3, wiki: "Ammonoidea" },
  { answer: "Archaeopteryx", aliases: [], category: "Fossil", tier: 3 },
  { answer: "Triceratops", aliases: [], category: "Dinosaur", tier: 3 },
  { answer: "Velociraptor", aliases: [], category: "Dinosaur", tier: 3 },
  { answer: "Stegosaurus", aliases: [], category: "Dinosaur", tier: 3 },
  { answer: "Platypus", aliases: ["duck billed platypus"], category: "Animal", tier: 3 },
  { answer: "Axolotl", aliases: ["axolotls", "mexican salamander", "walking fish"], category: "Animal", tier: 3 },
  { answer: "Red Panda", aliases: ["firefox"], category: "Animal", tier: 3, wiki: "Red panda" },
  { answer: "Meerkat", aliases: ["meerkats"], category: "Animal", tier: 3 },
  { answer: "Capybara", aliases: ["capybaras"], category: "Animal", tier: 3 },
  { answer: "Sloth", aliases: ["sloths"], category: "Animal", tier: 3 },
  { answer: "Chameleon", aliases: ["chameleons"], category: "Animal", tier: 3 },
  { answer: "Komodo Dragon", aliases: ["komodo", "komodo dragons"], category: "Animal", tier: 3 },
  { answer: "Narwhal", aliases: ["narwhals", "narwhale", "sea unicorn"], category: "Animal", tier: 3 },
  { answer: "Pufferfish", aliases: ["blowfish", "puffer fish", "fugu"], category: "Animal", tier: 3, wiki: "Tetraodontidae" },
  { answer: "Anglerfish", aliases: ["angler fish"], category: "Animal", tier: 3 },
  { answer: "Mantis Shrimp", aliases: ["mantis shrimps"], category: "Animal", tier: 3 },
  { answer: "Clownfish", aliases: ["clown fish", "anemonefish", "nemo fish"], category: "Animal", tier: 3 },
  { answer: "Seahorse", aliases: ["sea horse", "seahorses"], category: "Animal", tier: 3 },
  { answer: "Poison Dart Frog", aliases: ["poison arrow frog", "dart frog", "poison dart frogs"], category: "Animal", tier: 3 },
  { answer: "Praying Mantis", aliases: ["mantis", "praying mantids"], category: "Animal", tier: 3, wiki: "Mantis" },
  { answer: "Ladybug", aliases: ["ladybird", "ladybugs", "ladybirds", "lady beetle"], category: "Animal", tier: 3, wiki: "Coccinellidae" },
  { answer: "Tardigrade", aliases: ["water bear", "waterbear"], category: "Biology", tier: 3 },
  { answer: "Neuron", aliases: ["nerve cell", "neurons", "neurone"], category: "Biology", tier: 3 },
  { answer: "Bacteria", aliases: ["bacterium"], category: "Biology", tier: 3 },
  { answer: "Petri Dish", aliases: ["petri dish"], category: "Medicine", tier: 3 },
  { answer: "Geiger Counter", aliases: ["geiger counter"], category: "Physics", tier: 3 },
  { answer: "Cloud Chamber", aliases: ["cloud chambers"], category: "Physics", tier: 3 },
  { answer: "Superconductor", aliases: ["superconductivity", "superconducting magnet"], category: "Physics", tier: 3, wiki: "Superconductivity" },
  { answer: "Large Hadron Collider", aliases: ["lhc", "hadron collider"], category: "Physics", tier: 3 },
  { answer: "Gyroscope", aliases: ["gyroscopes"], category: "Physics", tier: 3 },
  { answer: "Pendulum", aliases: ["pendulums"], category: "Physics", tier: 3 },
  { answer: "Foucault Pendulum", aliases: ["foucaults pendulum"], category: "Physics", tier: 3 },
  { answer: "Cathode Ray Tube", aliases: ["crt"], category: "Physics", tier: 3 },
  { answer: "Vacuum Tube", aliases: ["thermionic valve", "electron tube", "vacuum tubes"], category: "Physics", tier: 3 },
  { answer: "Transistor", aliases: ["transistors"], category: "Physics", tier: 3 },
  { answer: "Periodic Table", aliases: ["the periodic table", "periodic table of elements"], category: "Chemistry", tier: 3 },
  { answer: "Buckyball", aliases: ["buckminsterfullerene", "c60", "fullerene", "bucky ball"], category: "Chemistry", tier: 3, wiki: "Buckminsterfullerene" },
  { answer: "Benzene", aliases: ["benzene ring"], category: "Chemistry", tier: 3 },
  { answer: "Aspirin", aliases: ["acetylsalicylic acid"], category: "Chemistry", tier: 3 },
  { answer: "Erlenmeyer Flask", aliases: ["erlenmeyer", "conical flask"], category: "Chemistry", tier: 3 },
  { answer: "Bunsen Burner", aliases: ["bunsen"], category: "Chemistry", tier: 3 },
  { answer: "Test Tube", aliases: ["test tubes", "testtube"], category: "Chemistry", tier: 3 },
  { answer: "Graduated Cylinder", aliases: ["measuring cylinder", "graduated cylinders"], category: "Chemistry", tier: 3 },
  { answer: "Volumetric Flask", aliases: ["volumetric flasks"], category: "Chemistry", tier: 3 },
  { answer: "Dmitri Mendeleev", aliases: ["mendeleev"], category: "Scientist", tier: 3 },
  { answer: "Rosalind Franklin", aliases: ["franklin"], category: "Scientist", tier: 3 },
  { answer: "Max Planck", aliases: ["planck"], category: "Scientist", tier: 3 },
  { answer: "Niels Bohr", aliases: ["bohr"], category: "Scientist", tier: 3 },
  { answer: "Erwin Schrödinger", aliases: ["schrodinger"], category: "Scientist", tier: 3 },
  { answer: "Werner Heisenberg", aliases: ["heisenberg"], category: "Scientist", tier: 3 },
  { answer: "Richard Feynman", aliases: ["feynman"], category: "Scientist", tier: 3 },
  { answer: "James Clerk Maxwell", aliases: ["maxwell", "clerk maxwell"], category: "Scientist", tier: 3 },
  { answer: "Antoine Lavoisier", aliases: ["lavoisier"], category: "Scientist", tier: 3 },
  { answer: "Homer", aliases: ["homer poet"], category: "Author", tier: 3 },
  { answer: "Dante Alighieri", aliases: ["dante"], category: "Author", tier: 3 },
  { answer: "Miguel de Cervantes", aliases: ["cervantes"], category: "Author", tier: 3 },
  { answer: "Charles Dickens", aliases: ["dickens"], category: "Author", tier: 3 },
  { answer: "Mark Twain", aliases: ["twain", "samuel clemens"], category: "Author", tier: 3 },
  { answer: "Jane Austen", aliases: ["austen"], category: "Author", tier: 3 },
  { answer: "Edgar Allan Poe", aliases: ["poe", "edgar allen poe"], category: "Author", tier: 3 },
  { answer: "Franz Kafka", aliases: ["kafka"], category: "Author", tier: 3 },
  { answer: "George Orwell", aliases: ["orwell", "eric blair"], category: "Author", tier: 3 },
  { answer: "Fyodor Dostoevsky", aliases: ["dostoevsky", "dostoyevsky"], category: "Author", tier: 3 },
  { answer: "Leo Tolstoy", aliases: ["tolstoy"], category: "Author", tier: 3 },
  { answer: "Victor Hugo", aliases: ["hugo"], category: "Author", tier: 3 },
  { answer: "J. R. R. Tolkien", aliases: ["tolkien", "jrr tolkien", "j r r tolkien"], category: "Author", tier: 3 },
  { answer: "Johannes Gutenberg", aliases: ["gutenberg"], category: "History", tier: 3 },
  { answer: "Book of Kells", aliases: ["the book of kells"], category: "Book", tier: 3 },
  { answer: "Gutenberg Bible", aliases: ["the gutenberg bible"], category: "Book", tier: 3 },
  { answer: "Rosetta Stone", aliases: ["the rosetta stone"], category: "History", tier: 3 },
  { answer: "Voynich Manuscript", aliases: ["the voynich manuscript"], category: "Book", tier: 3 },
  { answer: "Egyptian Hieroglyphs", aliases: ["hieroglyphics", "hieroglyphs", "hieroglyph"], category: "History", tier: 3 },
  { answer: "Cuneiform", aliases: ["cuneiform writing", "cuneiform script"], category: "History", tier: 3 },
  { answer: "Papyrus", aliases: ["papyrus paper"], category: "History", tier: 3 },
  { answer: "First Folio", aliases: ["the first folio", "shakespeare first folio"], category: "Book", tier: 3 },
  { answer: "Epic of Gilgamesh", aliases: ["gilgamesh", "the epic of gilgamesh"], category: "Book", tier: 3 },
  { answer: "Theremin", aliases: ["theramins"], category: "Music", tier: 3 },
  { answer: "Bagpipes", aliases: ["bagpipe"], category: "Music", tier: 3 },
  { answer: "Didgeridoo", aliases: ["didjeridu"], category: "Music", tier: 3 },
  { answer: "Sitar", aliases: ["sitars"], category: "Music", tier: 3 },
  { answer: "Harmonica", aliases: ["mouth organ", "blues harp"], category: "Music", tier: 3 },
  { answer: "Cello", aliases: ["violoncello"], category: "Music", tier: 3 },
  { answer: "Chopin", aliases: ["frederic chopin"], category: "Composer", tier: 3, wiki: "Frédéric Chopin" },
  { answer: "Tchaikovsky", aliases: ["pyotr ilyich tchaikovsky", "chaikovsky"], category: "Composer", tier: 3, wiki: "Pyotr Ilyich Tchaikovsky" },
  { answer: "Louis Armstrong", aliases: ["satchmo", "louie armstrong"], category: "Person", tier: 3 },
  { answer: "Elvis Presley", aliases: ["elvis"], category: "Person", tier: 3 },
  { answer: "The Birth of Venus", aliases: ["birth of venus", "botticelli venus"], category: "Artwork", tier: 3 },
  { answer: "The Creation of Adam", aliases: ["creation of adam"], category: "Artwork", tier: 3 },
  { answer: "The Last Supper", aliases: ["last supper"], category: "Artwork", tier: 3, wiki: "The Last Supper (Leonardo)" },
  { answer: "The Night Watch", aliases: ["night watch", "the nightwatch", "de nachtwacht"], category: "Artwork", tier: 3 },
  { answer: "Liberty Leading the People", aliases: [], category: "Artwork", tier: 3 },
  { answer: "Impression, Sunrise", aliases: ["impression sunrise", "impression soleil levant", "monet sunrise"], category: "Artwork", tier: 3 },
  { answer: "Wanderer above the Sea of Fog", aliases: ["the wanderer above the sea of fog", "wanderer above the mist"], category: "Artwork", tier: 3, wiki: "Wanderer Above the Sea of Fog" },
  { answer: "The Garden of Earthly Delights", aliases: ["garden of earthly delights"], category: "Artwork", tier: 3 },
  { answer: "A Sunday Afternoon on the Island of La Grande Jatte", aliases: ["la grande jatte", "a sunday on la grande jatte", "seurat grande jatte"], category: "Artwork", tier: 3 },
  { answer: "Water Lilies", aliases: ["les nympheas", "monet water lilies", "the water lilies"], category: "Artwork", tier: 3, wiki: "Water Lilies (Monet series)" },
  { answer: "Anubis", aliases: [], category: "Mythology", tier: 3 },
  { answer: "Zeus", aliases: ["jupiter god"], category: "Mythology", tier: 3 },
  { answer: "Thor", aliases: [], category: "Mythology", tier: 3 },
  { answer: "Odin", aliases: ["woden", "wotan"], category: "Mythology", tier: 3 },
  { answer: "Valkyrie", aliases: ["valkyries", "walkyrie"], category: "Mythology", tier: 3 },
  { answer: "Dragon", aliases: ["dragons"], category: "Mythology", tier: 3 },
  { answer: "Griffin", aliases: ["griffon", "gryphon"], category: "Mythology", tier: 3 },
  { answer: "Phoenix", aliases: ["phoenix bird"], category: "Mythology", tier: 3, wiki: "Phoenix (mythology)" },
  { answer: "Kraken", aliases: ["the kraken"], category: "Mythology", tier: 3 },
  { answer: "Centaur", aliases: ["centaurs"], category: "Mythology", tier: 3 },
  { answer: "Medusa", aliases: [], category: "Mythology", tier: 3 },
  { answer: "Minotaur", aliases: ["the minotaur"], category: "Mythology", tier: 3 },
  { answer: "Go", aliases: ["go game", "baduk", "weiqi", "igo"], category: "Game", tier: 3, wiki: "Go (game)" },
  { answer: "Mahjong", aliases: ["mah jongg", "mah jong"], category: "Game", tier: 3 },
  { answer: "Dungeons & Dragons", aliases: ["dnd", "dungeons and dragons"], category: "Game", tier: 3 },
  { answer: "The Legend of Zelda", aliases: ["zelda", "legend of zelda"], category: "Game", tier: 3 },
  { answer: "Grand Theft Auto", aliases: ["gta"], category: "Game", tier: 3 },
  { answer: "Kaleidoscope", aliases: ["kaleidoscopes"], category: "Object", tier: 3 },
  { answer: "Rubber Duck", aliases: ["rubber ducky", "ducky"], category: "Object", tier: 3 },
  { answer: "Paper Clip", aliases: ["paperclip", "paper clips"], category: "Object", tier: 3 },
  { answer: "Zipper", aliases: ["zip", "zip fastener"], category: "Object", tier: 3 },
  { answer: "Velcro", aliases: ["hook and loop"], category: "Object", tier: 3 },
  { answer: "Pocket Watch", aliases: ["pocketwatch"], category: "Object", tier: 3 },
  { answer: "Sextant", aliases: ["sextants"], category: "Object", tier: 3 },
  { answer: "Astrolabe", aliases: ["astrolabes"], category: "Object", tier: 3 },
  { answer: "Abacus", aliases: ["abacuses", "abaci"], category: "Object", tier: 3 },
  { answer: "Jukebox", aliases: ["jukeboxes"], category: "Object", tier: 3 },
  { answer: "Dice", aliases: ["die", "dices"], category: "Object", tier: 3 },
  { answer: "Padlock", aliases: ["padlocks", "lock"], category: "Object", tier: 3 },
  { answer: "Solar Panel", aliases: ["solar panels", "solar cell"], category: "Object", tier: 3 },
  { answer: "Windmill", aliases: ["windmills", "dutch windmill"], category: "Object", tier: 3 },
  { answer: "Lighthouse", aliases: ["lighthouses"], category: "Object", tier: 3 },
  { answer: "Concorde", aliases: ["concord plane", "concorde jet", "the concorde"], category: "Vehicle", tier: 3 },
  { answer: "Model T", aliases: ["ford model t", "model t ford", "tin lizzie"], category: "Vehicle", tier: 3, wiki: "Ford Model T" },
  { answer: "Submarine", aliases: ["submarines", "sub"], category: "Vehicle", tier: 3 },
  { answer: "Steam Locomotive", aliases: ["steam train", "steam engine"], category: "Vehicle", tier: 3 },
  { answer: "Hot Air Balloon", aliases: ["hot air balloons"], category: "Vehicle", tier: 3, wiki: "Hot air balloon" },
  { answer: "Bicycle", aliases: ["bike", "bicycles"], category: "Vehicle", tier: 3 },
  { answer: "Ice Hockey", aliases: ["hockey"], category: "Sport", tier: 3 },
  { answer: "Fencing", aliases: ["sword fighting"], category: "Sport", tier: 3 },
  { answer: "Judo", aliases: [], category: "Sport", tier: 3 },
  { answer: "Curling", aliases: ["curling stone"], category: "Sport", tier: 3 },
  { answer: "Figure Skating", aliases: ["iceskating", "ice skating"], category: "Sport", tier: 3 },
  { answer: "Rock Climbing", aliases: ["climbing", "rockclimbing"], category: "Sport", tier: 3 },
  { answer: "Darts", aliases: ["dart", "darts game"], category: "Sport", tier: 3 },
  { answer: "Snooker", aliases: ["snooker table"], category: "Sport", tier: 3 },
  { answer: "Badminton", aliases: ["badminton racket", "shuttlecock"], category: "Sport", tier: 3 },
  { answer: "Poker", aliases: ["poker cards", "poker game"], category: "Game", tier: 3 },
  { answer: "Roulette", aliases: ["roulette wheel"], category: "Game", tier: 3 },
  { answer: "Pluto", aliases: ["planet pluto", "dwarf planet pluto"], category: "Space", tier: 3 },
  { answer: "Neptune", aliases: ["planet neptune"], category: "Space", tier: 3 },
  { answer: "Uranus", aliases: ["planet uranus"], category: "Space", tier: 3 },
  { answer: "Europa", aliases: ["europa moon", "jupiter moon"], category: "Space", tier: 3, wiki: "Europa (moon)" },
  { answer: "Titan", aliases: ["titan moon", "saturn moon"], category: "Space", tier: 3, wiki: "Titan (moon)" },
  { answer: "Orion Nebula", aliases: [], category: "Space", tier: 3 },
  { answer: "Crab Nebula", aliases: [], category: "Space", tier: 3 },
  { answer: "Black Hole", aliases: ["blackhole", "event horizon"], category: "Space", tier: 3, wiki: "Black hole" },
  { answer: "Halley's Comet", aliases: ["halleys comet", "halley comet"], category: "Space", tier: 3 },
  { answer: "Voyager 1", aliases: ["voyager probe", "voyager spacecraft"], category: "Space", tier: 3 },
  { answer: "James Webb Space Telescope", aliases: ["jwst", "webb telescope", "james webb"], category: "Space", tier: 3 },
  { answer: "Meteorite", aliases: ["meteorites", "meteor"], category: "Space", tier: 3 },
  { answer: "Ostrich", aliases: ["ostriches"], category: "Animal", tier: 3 },
  { answer: "Hedgehog", aliases: ["hedgehogs"], category: "Animal", tier: 3 },
  { answer: "Raccoon", aliases: ["racoon", "racoons", "raccoons"], category: "Animal", tier: 3 },
  { answer: "Beaver", aliases: ["beavers"], category: "Animal", tier: 3 },
  { answer: "Otter", aliases: ["otters"], category: "Animal", tier: 3 },
  { answer: "Llama", aliases: ["llamas"], category: "Animal", tier: 3 },
  { answer: "Snow Leopard", aliases: [], category: "Animal", tier: 3 },
  { answer: "Orangutan", aliases: ["orangutang", "orangutans"], category: "Animal", tier: 3 },
  { answer: "Chimpanzee", aliases: ["chimp", "chimps", "chimpanzees"], category: "Animal", tier: 3 },
  { answer: "Lemur", aliases: ["lemurs"], category: "Animal", tier: 3 },
  { answer: "Armadillo", aliases: ["armadillos"], category: "Animal", tier: 3 },
  { answer: "King Cobra", aliases: ["cobra", "cobras"], category: "Animal", tier: 3 },
  { answer: "Alligator", aliases: ["alligators", "gator"], category: "Animal", tier: 3 },
  { answer: "Sea Turtle", aliases: ["seaturtle", "sea turtles", "turtle"], category: "Animal", tier: 3 },
  { answer: "Starfish", aliases: ["star fish", "sea star"], category: "Animal", tier: 3 },
  { answer: "Sea Urchin", aliases: ["sea urchins", "urchin"], category: "Animal", tier: 3 },
  { answer: "Snail", aliases: ["snails"], category: "Animal", tier: 3 },
  { answer: "Fly Agaric", aliases: ["amanita muscaria", "amanita", "toadstool"], category: "Nature", tier: 3, wiki: "Amanita muscaria" },
  { answer: "Giant Sequoia", aliases: ["sequoia", "redwood", "giant redwood"], category: "Plant", tier: 3, wiki: "Sequoiadendron giganteum" },
  { answer: "Lavender", aliases: ["lavandula"], category: "Plant", tier: 3, wiki: "Lavandula" },
  { answer: "Tulip", aliases: ["tulips"], category: "Plant", tier: 3 },
  { answer: "Rose", aliases: ["roses", "rose flower"], category: "Plant", tier: 3 },
  { answer: "Orchid", aliases: ["orchids"], category: "Plant", tier: 3 },
  { answer: "Mushroom", aliases: ["mushrooms", "fungi"], category: "Nature", tier: 3 },
  { answer: "QR Code", aliases: ["qr code", "quick response code", "qrcode"], category: "Tech", tier: 3, wiki: "QR code" },
  { answer: "Barcode", aliases: ["barcodes", "bar code", "upc"], category: "Tech", tier: 3 },
  { answer: "3D Printer", aliases: ["3d printing", "three d printer"], category: "Tech", tier: 3, wiki: "3D printing" },
  { answer: "Drone", aliases: ["drones", "uav", "unmanned aerial vehicle", "quadcopter"], category: "Tech", tier: 3, wiki: "Unmanned aerial vehicle" },
  { answer: "Motherboard", aliases: ["mainboard", "logic board", "mobo"], category: "Tech", tier: 3 },
  { answer: "USB Flash Drive", aliases: ["usb stick", "usb drive", "thumb drive", "memory stick", "pen drive"], category: "Tech", tier: 3 },
  { answer: "Hard Disk Drive", aliases: ["hard drive", "hard disk", "hdd"], category: "Tech", tier: 3 },
  { answer: "Microprocessor", aliases: ["cpu", "processor", "micro chip", "microchip"], category: "Tech", tier: 3 },
  { answer: "MRI Machine", aliases: ["mri", "magnetic resonance imaging", "mri scanner"], category: "Medicine", tier: 3, wiki: "Magnetic resonance imaging" },
  { answer: "Penicillin", aliases: ["penicillium", "penicillin mold"], category: "Medicine", tier: 3 },
  { answer: "Vaccine", aliases: ["vaccination", "vaccines"], category: "Medicine", tier: 3, wiki: "Vaccination" }
];
